from pathlib import Path
import json,hashlib,subprocess,shutil
repo=Path('/home/exedev/js-wf');r=Path('/tmp/js-wf-postgres-projection-fault-50000-20261005');out=repo/'docs/scale/postgres-projection-fault-50000-2026-10-05/failed';out.mkdir(parents=True,exist_ok=True)
def sha(p):
 with p.open('rb') as f:return hashlib.file_digest(f,'sha256').hexdigest()
e=json.load(open(r/'execution.json'));b=json.load(open(r/'binary.json'));assert e['status']=='failed' and e['exit_code']==1 and not Path(f"/proc/{e['pid']}").exists();assert sha(r/'integration.test')==e['sha256']==b['sha256'] and e['build_info'].splitlines()[1:]==b['build_info'].splitlines()[1:] and 'vcs.modified=false' in b['build_info'] and '-race=true' not in b['build_info'] and 'vcs.revision='+e['source'] in b['build_info']
before=json.load(open(r/'source-before.json'));assert before==json.load(open(r/'source-after.json')) and before['revision']==e['source']
for n,d in before['files'].items():assert sha(r/'source'/n)==d==hashlib.sha256(subprocess.check_output(['git','show',e['source']+':'+n],cwd=repo)).hexdigest()
external=json.load(open(r/'external-source-before.json'));assert external==json.load(open(r/'external-source-after.json'));paths=json.load(open(r/'external-captured-paths.json'));assert set(paths)==set(external)
for n,d in external.items():assert sha(r/paths[n])==d
p=next((r/'originals').rglob('projection-fault-proof.json'));proof=json.load(open(p));assert proof['count']==50000 and proof['postgres_fault'] and proof['native_test_failed'] and proof['all_results_checked_while_projection_stopped'] and proof['stopped_projection_lag']==100000 and proof['projection_process_reaped_sigkill'];assert proof['actual_projection_sdk_sha256']==e['sha256'] and proof['actual_projection_sdk_build_info'].splitlines()[1:]==b['build_info'].splitlines()[1:] and not Path(f"/proc/{proof['actual_projection_sdk_pid']}").exists();assert proof['writer_backend_termination_confirmed'] and 0<proof['catchup_admitted_rows']==31<50000 and 'writer lock session lost' in proof['faulted_projection_error'] and proof['journal_leader_old_server_id']!=proof['journal_leader_new_server_id'] and proof['journal_all_three_replicas_current']
pg=json.load(open(r/'actual-postgres.json'));assert sha(r/'actual-postgres')==pg['actual_executable_sha256'];stopped=json.load(open(r/'postgres-stopped.json'));assert not stopped['State']['Running'] and stopped['State']['Pid']==0 and stopped['Id']==pg['container']['Id'];media=json.load(open(r/'postgres-media-copy-verification.json'));assert media['all_closed_sql_media_bytes_match']
for n,d in media['files'].items():assert sha(r/'postgres-stopped-data'/n)==d
log=(r/'native.log').read_text();assert 'started 50000 invocations' in log and 'completed and checked 50000 results' in log and 'restarted projection exited before lag drained: nats: no responders available for request' in log and 'FAIL' in log
review={'source':e['source'],'actual_parent_sdk_sha256':e['sha256'],'actual_killed_projection_sdk_sha256':proof['actual_projection_sdk_sha256'],'selected_git_inputs_verified':len(before['files']),'selected_external_inputs_verified':len(external),'actual_postgres_executable_sha256':pg['actual_executable_sha256'],'actual_postgres_version':pg['version'],'closed_postgres_media_files_verified':len(media['files']),'native_failed_seconds':405.60,'count':50000,'results_checked_before_fault':50000,'stopped_projection_lag':100000,'confirmed_partial_catchup_rows':31,'writer_session_termination_and_library_journal_restart_admitted':True,'replacement_projection_failed_no_responders':True,'secondary_cleanup_connection_closed_errors':True,'library_restart_replaces_pinned_client_handles':True,'no_responder_cause_confirmed':False,'full_lag_zero_and_rebuild_equality_not_reached':True,'qualifies_fault_recovery_or_full_matrix_or_24h':False,'limitations':['Real R3 servers are embedded in SDK, no separate NATS server process hashes or logs.','PostgreSQL server process remained live until post-SDK graceful stop; no SQL server SIGKILL claim.','Source/API assertions bind full workflow results and fault admission; original failed run stays failed.','Selected input inventory excludes exhaustive race/assembly/embed/compiler provenance.','Shares VM with two live campaigns; no pressure attribution.']}
(r/'independent-review.json').write_text(json.dumps(review,indent=2)+'\n');shutil.copy2(__file__,r/'executed-review.py')
for n in ['execution.json','independent-review.json','executed-producer.py','executed-review.py','actual-postgres.json']:shutil.copy2(r/n,out/n)
shutil.copy2(p,out/p.name);shutil.copy2('/tmp/js-wf-preserve-read-proof-20261005.py',out/'executed-preserver.py');print(json.dumps(review))
