#!/usr/bin/env python3
"""Run the original R3 real WatchAll creation-stall component with retained inputs."""
import argparse
import datetime
import hashlib
import importlib.util
import json
import os
from pathlib import Path
import shutil
import subprocess
import time

import fixture_archive
import live_process_admission

REPO = Path(__file__).resolve().parents[1]
TEST = 'TestStateCreationNativeRecovery'


def sha(path):
    with Path(path).open('rb') as stream:
        return hashlib.file_digest(stream, 'sha256').hexdigest()


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--root', type=Path, required=True)
    args = parser.parse_args()
    root = args.root
    assert root.is_absolute() and not root.exists() and not root.is_symlink() and not root.resolve().is_relative_to(REPO)
    assert not subprocess.check_output(['git', 'status', '--porcelain'], cwd=REPO), 'clean source required'
    revision = subprocess.check_output(['git', 'rev-parse', 'HEAD'], cwd=REPO, text=True).strip()
    root.mkdir(mode=0o700)
    save = lambda name, value: (root/name).write_text(json.dumps(value, indent=2)+'\n')
    names = subprocess.check_output(['git', 'ls-files', '*.go', 'go.mod', 'go.sum'], cwd=REPO, text=True).splitlines()
    names += ['scripts/run-state-creation-native.py', 'scripts/live_process_admission.py', 'scripts/fixture_archive.py', 'scripts/fixture_delta.py', 'scripts/verify-tier2-closed-originals.py']
    before = {}
    for name in names:
        original = subprocess.check_output(['git', 'cat-file', 'blob', revision+':'+name], cwd=REPO)
        assert hashlib.sha256(original).hexdigest() == sha(REPO/name)
        before[name] = sha(REPO/name)
        target = root/'selected-source'/name
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(REPO/name, target)
    save('source-before.json', dict(revision=revision, files=before))
    env = {k:v for k,v in os.environ.items() if not k.startswith(('WF_', 'MATRIX_', 'TIER3_MATRIX_'))}
    env.update(GOMAXPROCS='2', GOMEMLIMIT='1GiB', GOWORK='off', GOFLAGS='', WF_STATE_CREATION_ROOT=str(root/'fixture'))
    fmt = '{{.Dir}}|{{join .GoFiles " "}}|{{join .CgoFiles " "}}|{{join .TestGoFiles " "}}|{{join .XTestGoFiles " "}}'
    dependencies = subprocess.check_output(['go', 'list', '-deps', '-test', '-f', fmt, './integrity'], cwd=REPO, env=env, text=True)
    (root/'dependencies.txt').write_text(dependencies)
    goroot = Path(subprocess.check_output(['go', 'env', 'GOROOT'], env=env, text=True).strip())
    modules = Path(subprocess.check_output(['go', 'env', 'GOMODCACHE'], env=env, text=True).strip())
    external, captured, generated = {}, {}, {}
    for line in dependencies.splitlines():
        directory, *groups = line.split('|')
        for name in ' '.join(groups).split():
            path = (Path(directory)/name).resolve()
            if not path.is_file() or path.is_relative_to(REPO) or str(path) in external:
                continue
            relative = Path('modules')/path.relative_to(modules) if path.is_relative_to(modules) else Path('toolchain')/path.relative_to(goroot) if path.is_relative_to(goroot) else Path('other')/str(path).lstrip('/')
            target = root/'external-source'/relative
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(path, target)
            digest = sha(path)
            assert sha(target) == digest
            if b"// Code generated by 'go test'. DO NOT EDIT." in path.read_bytes()[:120]:
                generated[str(path)] = dict(sha256=digest, captured=str(target.relative_to(root)))
            else:
                external[str(path)] = digest
                captured[str(path)] = str(target.relative_to(root))
    save('generated-inputs.json', generated)
    save('external-source-before.json', external)
    save('external-captured-paths.json', captured)
    binary = root/'integrity-race.test'
    build = ['go', 'test', '-race', '-buildvcs=true', '-c', '-o', str(binary), './integrity']
    run = [str(binary), '-test.v', '-test.run=^'+TEST+'$', '-test.count=1', '-test.timeout=2m']
    profile = {key:env[key] for key in ['GOMAXPROCS', 'GOMEMLIMIT', 'GOWORK', 'GOFLAGS', 'WF_STATE_CREATION_ROOT']}
    save('commands.json', dict(build=build, run=run, cwd=str(REPO), environment=profile))
    shutil.copyfile(__file__, root/'executed-producer.py')
    with (root/'build.log').open('w') as log:
        subprocess.run(build, cwd=REPO, env=env, stdout=log, stderr=subprocess.STDOUT, check=True)
    info = subprocess.check_output(['go', 'version', '-m', str(binary)], text=True)
    assert '-race=true' in info and 'vcs.modified=false' in info and 'vcs.revision='+revision in info
    save('binary.json', dict(sha256=sha(binary), build_info=info))
    started = time.monotonic()
    with (root/'native.log').open('w') as log:
        child = subprocess.Popen(run, cwd=REPO, env=env, stdout=log, stderr=subprocess.STDOUT)
        actual = live_process_admission.admit(child, run, profile, REPO, binary, sha(binary))
        save('actual-sdk.json', actual)
        print('ACTUAL_NATIVE_STATE_CREATION_SDK', child.pid, flush=True)
        code = child.wait()
    save('execution.json', dict(source=revision, native_exit_code=code, elapsed_seconds=time.monotonic()-started, finished_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(), scope='Original R3 component only; no R5/full-cohort/24h qualification'))
    after = {name:sha(REPO/name) for name in names}
    save('source-after.json', dict(revision=revision, files=after))
    assert before == after and revision == subprocess.check_output(['git', 'rev-parse', 'HEAD'], cwd=REPO, text=True).strip()
    external_after = {name:sha(name) for name in external}
    save('external-source-after.json', external_after)
    assert external == external_after
    spec = importlib.util.spec_from_file_location('closed', REPO/'scripts/verify-tier2-closed-originals.py')
    closed = importlib.util.module_from_spec(spec); spec.loader.exec_module(closed)
    save('closure.json', closed.verify_no_open_originals(root))
    proof = fixture_archive.capture(root, Path(str(root)+'.tar.gz'), root.with_name(root.name+'-proof'), compresslevel=1)
    print(json.dumps(dict(native_exit_code=code, archive=proof)), flush=True)
    assert code == 0, 'original native component failed; failed fixture retained'


if __name__ == '__main__':
    main()
