// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: protocol/v1/journal.proto

package protocolv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EntryKind int32

const (
	EntryKind_ENTRY_KIND_UNSPECIFIED     EntryKind = 0
	EntryKind_ENTRY_KIND_STARTED         EntryKind = 1
	EntryKind_ENTRY_KIND_STEP_REQUESTED  EntryKind = 2
	EntryKind_ENTRY_KIND_STEP_COMPLETED  EntryKind = 3
	EntryKind_ENTRY_KIND_SUSPENDED       EntryKind = 4
	EntryKind_ENTRY_KIND_SIGNAL_CONSUMED EntryKind = 5
	EntryKind_ENTRY_KIND_ATTEMPT         EntryKind = 6
	EntryKind_ENTRY_KIND_COMPLETED       EntryKind = 7
	EntryKind_ENTRY_KIND_FAILED          EntryKind = 8
)

// Enum value maps for EntryKind.
var (
	EntryKind_name = map[int32]string{
		0: "ENTRY_KIND_UNSPECIFIED",
		1: "ENTRY_KIND_STARTED",
		2: "ENTRY_KIND_STEP_REQUESTED",
		3: "ENTRY_KIND_STEP_COMPLETED",
		4: "ENTRY_KIND_SUSPENDED",
		5: "ENTRY_KIND_SIGNAL_CONSUMED",
		6: "ENTRY_KIND_ATTEMPT",
		7: "ENTRY_KIND_COMPLETED",
		8: "ENTRY_KIND_FAILED",
	}
	EntryKind_value = map[string]int32{
		"ENTRY_KIND_UNSPECIFIED":     0,
		"ENTRY_KIND_STARTED":         1,
		"ENTRY_KIND_STEP_REQUESTED":  2,
		"ENTRY_KIND_STEP_COMPLETED":  3,
		"ENTRY_KIND_SUSPENDED":       4,
		"ENTRY_KIND_SIGNAL_CONSUMED": 5,
		"ENTRY_KIND_ATTEMPT":         6,
		"ENTRY_KIND_COMPLETED":       7,
		"ENTRY_KIND_FAILED":          8,
	}
)

func (x EntryKind) Enum() *EntryKind {
	p := new(EntryKind)
	*p = x
	return p
}

func (x EntryKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntryKind) Descriptor() protoreflect.EnumDescriptor {
	return file_protocol_v1_journal_proto_enumTypes[0].Descriptor()
}

func (EntryKind) Type() protoreflect.EnumType {
	return &file_protocol_v1_journal_proto_enumTypes[0]
}

func (x EntryKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntryKind.Descriptor instead.
func (EntryKind) EnumDescriptor() ([]byte, []int) {
	return file_protocol_v1_journal_proto_rawDescGZIP(), []int{0}
}

// Versioned interchange envelope. Protobuf WF_JRN storage requires the WFJ-NUL
// prefix and sequence=0, documented in docs/journal-protocol.md. Bare envelope
// bytes are not a WF_JRN storage publish. JSON remains the default writer.
type JournalRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`   // Must be 1. Zero/unknown versions are rejected.
	Sequence      uint64                 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"` // Physical JetStream sequence; zero for an unbound entry.
	Entry         *JournalEntry          `protobuf:"bytes,3,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JournalRecord) Reset() {
	*x = JournalRecord{}
	mi := &file_protocol_v1_journal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JournalRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JournalRecord) ProtoMessage() {}

func (x *JournalRecord) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_v1_journal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JournalRecord.ProtoReflect.Descriptor instead.
func (*JournalRecord) Descriptor() ([]byte, []int) {
	return file_protocol_v1_journal_proto_rawDescGZIP(), []int{0}
}

func (x *JournalRecord) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *JournalRecord) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *JournalRecord) GetEntry() *JournalEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

type JournalEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Epoch uint64                 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Index uint64                 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Kind  EntryKind              `protobuf:"varint,3,opt,name=kind,proto3,enum=jetstream.workflow.v1.EntryKind" json:"kind,omitempty"`
	// Exact UTF-8 JSON bytes, not google.protobuf.Value or ProtoJSON. This keeps
	// integers, whitespace, null, object references and hash inputs intact.
	PayloadJson   []byte `protobuf:"bytes,4,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	WorkerId      string `protobuf:"bytes,5,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JournalEntry) Reset() {
	*x = JournalEntry{}
	mi := &file_protocol_v1_journal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JournalEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JournalEntry) ProtoMessage() {}

func (x *JournalEntry) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_v1_journal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JournalEntry.ProtoReflect.Descriptor instead.
func (*JournalEntry) Descriptor() ([]byte, []int) {
	return file_protocol_v1_journal_proto_rawDescGZIP(), []int{1}
}

func (x *JournalEntry) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *JournalEntry) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *JournalEntry) GetKind() EntryKind {
	if x != nil {
		return x.Kind
	}
	return EntryKind_ENTRY_KIND_UNSPECIFIED
}

func (x *JournalEntry) GetPayloadJson() []byte {
	if x != nil {
		return x.PayloadJson
	}
	return nil
}

func (x *JournalEntry) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

var File_protocol_v1_journal_proto protoreflect.FileDescriptor

const file_protocol_v1_journal_proto_rawDesc = "" +
	"\n" +
	"\x19protocol/v1/journal.proto\x12\x15jetstream.workflow.v1\"\x80\x01\n" +
	"\rJournalRecord\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x04R\bsequence\x129\n" +
	"\x05entry\x18\x03 \x01(\v2#.jetstream.workflow.v1.JournalEntryR\x05entry\"\xb0\x01\n" +
	"\fJournalEntry\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x04R\x05epoch\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x04R\x05index\x124\n" +
	"\x04kind\x18\x03 \x01(\x0e2 .jetstream.workflow.v1.EntryKindR\x04kind\x12!\n" +
	"\fpayload_json\x18\x04 \x01(\fR\vpayloadJson\x12\x1b\n" +
	"\tworker_id\x18\x05 \x01(\tR\bworkerId*\x80\x02\n" +
	"\tEntryKind\x12\x1a\n" +
	"\x16ENTRY_KIND_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12ENTRY_KIND_STARTED\x10\x01\x12\x1d\n" +
	"\x19ENTRY_KIND_STEP_REQUESTED\x10\x02\x12\x1d\n" +
	"\x19ENTRY_KIND_STEP_COMPLETED\x10\x03\x12\x18\n" +
	"\x14ENTRY_KIND_SUSPENDED\x10\x04\x12\x1e\n" +
	"\x1aENTRY_KIND_SIGNAL_CONSUMED\x10\x05\x12\x16\n" +
	"\x12ENTRY_KIND_ATTEMPT\x10\x06\x12\x18\n" +
	"\x14ENTRY_KIND_COMPLETED\x10\a\x12\x15\n" +
	"\x11ENTRY_KIND_FAILED\x10\bB\x1eZ\x1cjs-wf/protocol/v1;protocolv1b\x06proto3"

var (
	file_protocol_v1_journal_proto_rawDescOnce sync.Once
	file_protocol_v1_journal_proto_rawDescData []byte
)

func file_protocol_v1_journal_proto_rawDescGZIP() []byte {
	file_protocol_v1_journal_proto_rawDescOnce.Do(func() {
		file_protocol_v1_journal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protocol_v1_journal_proto_rawDesc), len(file_protocol_v1_journal_proto_rawDesc)))
	})
	return file_protocol_v1_journal_proto_rawDescData
}

var file_protocol_v1_journal_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protocol_v1_journal_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protocol_v1_journal_proto_goTypes = []any{
	(EntryKind)(0),        // 0: jetstream.workflow.v1.EntryKind
	(*JournalRecord)(nil), // 1: jetstream.workflow.v1.JournalRecord
	(*JournalEntry)(nil),  // 2: jetstream.workflow.v1.JournalEntry
}
var file_protocol_v1_journal_proto_depIdxs = []int32{
	2, // 0: jetstream.workflow.v1.JournalRecord.entry:type_name -> jetstream.workflow.v1.JournalEntry
	0, // 1: jetstream.workflow.v1.JournalEntry.kind:type_name -> jetstream.workflow.v1.EntryKind
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protocol_v1_journal_proto_init() }
func file_protocol_v1_journal_proto_init() {
	if File_protocol_v1_journal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protocol_v1_journal_proto_rawDesc), len(file_protocol_v1_journal_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protocol_v1_journal_proto_goTypes,
		DependencyIndexes: file_protocol_v1_journal_proto_depIdxs,
		EnumInfos:         file_protocol_v1_journal_proto_enumTypes,
		MessageInfos:      file_protocol_v1_journal_proto_msgTypes,
	}.Build()
	File_protocol_v1_journal_proto = out.File
	file_protocol_v1_journal_proto_goTypes = nil
	file_protocol_v1_journal_proto_depIdxs = nil
}
