from pathlib import Path
import json,hashlib,subprocess,shutil,collections,datetime
repo=Path('/home/exedev/js-wf');r=Path('/tmp/js-wf-fanout-last-predeadline-20261005');out=repo/'docs/scale/fanout-combined-boundaries-2026-10-05/last-predeadline';out.mkdir(parents=True,exist_ok=True)
def sha(p):
 with p.open('rb') as f:return hashlib.file_digest(f,'sha256').hexdigest()
e=json.load(open(r/'execution.json'));b=json.load(open(r/'binary.json'));assert e['status']=='failed' and e['exit_code']==1 and e['selected_case']=='results/last' and not e['full_six_boundary_selection'] and not Path(f"/proc/{e['pid']}").exists();assert sha(r/'integration.test')==e['sha256']==b['sha256'] and e['build_info'].splitlines()[1:]==b['build_info'].splitlines()[1:] and '-race=true' in b['build_info'] and 'vcs.modified=false' in b['build_info'] and 'vcs.revision='+e['source'] in b['build_info']
s=json.load(open(r/'source-before.json'));assert s==json.load(open(r/'source-after.json')) and s['revision']==e['source']
for n,d in s['files'].items():assert sha(r/'source'/n)==d==hashlib.sha256(subprocess.check_output(['git','show',e['source']+':'+n],cwd=repo)).hexdigest()
x=json.load(open(r/'external-source-before.json'));assert x==json.load(open(r/'external-source-after.json'));paths=json.load(open(r/'external-captured-paths.json'));assert set(x)==set(paths)
for n,d in x.items():assert sha(r/paths[n])==d
p=json.load(open(r/'producer-source.json'));producer=subprocess.check_output(['git','show',p['revision']+':'+p['path']],cwd=repo);assert p['revision']==e['source'] and hashlib.sha256(producer).hexdigest()==p['sha256']==sha(r/'executed-producer.py')
leaf=r/'originals/TestFiveHundredChildFanoutCombinedParentAndJournalBoundaryMatrix/results/last';a=json.load(open(leaf/'actual-parent-sdk-start.json'));assert a['actual_sdk_sha256']==e['sha256'] and a['actual_sdk_build_info'].splitlines()[1:]==b['build_info'].splitlines()[1:] and not Path(f"/proc/{a['pid']}").exists() and a['durable_prefix'] is None;assert not (leaf/'parent-cut').exists() and not (leaf/'journal-restart.json').exists() and not (leaf/'final-proof.json').exists()
raw=(leaf/'worker-trace.jsonl').read_text().splitlines();rows=[json.loads(l) for l in raw];assert rows[0]['kind']=='trace_started' and rows[0]['event']['pid']==a['pid'];stacks=[row['event'] for row in rows if row['kind']=='stack_captured'];assert len(stacks)==1 and stacks[0]['complete'] and (leaf/'worker-predeadline-stack.txt').stat().st_size==stacks[0]['bytes'];stack=(leaf/'worker-predeadline-stack.txt').read_text();assert 'journal.(*Store).loadSnapshot' in stack and 'encoding/json' in stack and 'worker.RunPartitionWithPort' in stack
began=datetime.datetime.fromisoformat(rows[0]['event']['at'].replace('Z','+00:00'));at=datetime.datetime.fromisoformat(stacks[0]['at'].replace('Z','+00:00'));assert 29<=(at-began).total_seconds()<30
ops=[row['event'] for row in rows if row['kind']=='operation'];dispatch=[row['event'] for row in rows if row['kind']=='dispatch'];assert ops and all(not o['Error'] for o in ops) and all(d['Type']=='parent' for d in dispatch)
per_delivery={}
for d in dispatch:
 k=f"{d['RunSequence']}/{d['Delivery']}";per_delivery.setdefault(k,[]).append(d['Stage'])
log=(r/'native.log').read_text();assert 'confirmed 489 outside child results before worker stop' in log and 'parent process did not reach child cut' in log and '--- FAIL:' in log
helper=subprocess.check_output(['git','show',e['source']+':scripts/check-fanout-boundary-matrix.py'],cwd=repo);(r/'executed-acceptance-checker.py').write_bytes(helper)
with (r/'converted-events.jsonl').open('w') as f:subprocess.run(['go','tool','test2json','-p','js-wf/integration'],input=log,text=True,stdout=f,check=True)
with (r/'acceptance-rejection.log').open('w') as f:result=subprocess.run(['python3',str(r/'executed-acceptance-checker.py'),'--combined','--events',str(r/'converted-events.jsonl'),'--output',str(r/'acceptance.json')],stdout=f,stderr=subprocess.STDOUT)
assert result.returncode!=0 and not (r/'acceptance.json').exists()
review={'source':e['source'],'actual_parent_and_child_sdk_sha256':e['sha256'],'native_status':'failed','native_seconds':95.28,'focused_case':'results/last','actual_fault_admitted':False,'selected_git_inputs_verified':len(s['files']),'selected_external_inputs_verified':len(x),'exact_producer_git_sha256':p['sha256'],'trace_records':len(rows),'operation_counts':dict(collections.Counter(o['Operation'] for o in ops)),'completed_operation_errors_observed':0,'dispatch_stages_per_delivery':per_delivery,'no_child_dispatch_observed':True,'predeadline_stack_seconds':(at-began).total_seconds(),'stack_complete_bytes':stacks[0]['bytes'],'stack_observed_snapshot_json_decode':True,'total_journal_append_seconds':sum(o['Duration'] for o in ops if o['Operation']=='journal_append')/1e9,'total_lease_renew_append_seconds':sum(o['Duration'] for o in ops if o['Operation']=='lease_renew_append')/1e9,'full_matrix_guard_rejected':True,'qualifies_full_combined_matrix':False,'qualifies_release_matrix_or_24h':False,'limitations':['Observations include instrumentation overhead.','Completed call timings do not isolate server from client/network/local cost or prove absence of unobserved errors.','One stack sample shows local decoding, not exhaustive causality.','Actual R3 library servers embedded in SDK; no separate server SIGKILL.','Original stores closed and not reopened.','Selected source excludes exhaustive assembly/embed/compiler provenance.']}
(r/'independent-review.json').write_text(json.dumps(review,indent=2)+'\n');shutil.copy2(__file__,r/'executed-review.py')
for n in ['independent-review.json','execution.json','executed-producer.py','executed-review.py','acceptance-rejection.log']:shutil.copy2(r/n,out/n)
print(json.dumps(review))
