from pathlib import Path
import json,hashlib,subprocess,shutil,datetime
repo=Path('/home/exedev/js-wf');r=Path('/tmp/js-wf-watch-observed-journal-24h-launch-proof-20261005');out=repo/'docs/scale/watch-observed-journal-24h-2026-10-05/launch';out.mkdir(parents=True,exist_ok=True)
def sha(p):
 with p.open('rb') as f:return hashlib.file_digest(f,'sha256').hexdigest()
e=json.loads((r/'execution.json').read_text());b=json.loads((r/'binary.json').read_text());before=json.loads((r/'source-before.json').read_text());assert e['status']=='running' and e['source']==before['revision'] and e['row']=='journal' and e['seed']==1 and e['duration']=='24h' and not e['race'] and e['memory_limit']=='2GiB' and e['retained_audit_trace'] and e['audit_wait_stack'] and e['streaming_state_retained_audit'] and e['explicit_route_seeds'] and e['journal_rollout']=='none'
assert sha(r/'integration.test')==b['sha256'] and 'vcs.modified=false' in b['build_info'] and 'vcs.revision='+e['source'] in b['build_info'] and '-race=true' not in b['build_info']
for n,d in before['files'].items():assert sha(r/'source'/n)==d==hashlib.sha256(subprocess.check_output(['git','show',e['source']+':'+n],cwd=repo)).hexdigest()
sdks=json.loads((r/'live-sdk-snapshot.json').read_text());assert len(sdks)==1
parent=sdks[0];pid=parent['pid'];assert parent['sha256']==b['sha256']==sha(Path(f'/proc/{pid}/exe'));assert parent['build_info'].splitlines()[1:]==b['build_info'].splitlines()[1:]
expected=json.loads((r/'test-environment.json').read_text());environment={x.split('=',1)[0]:x.split('=',1)[1] for x in Path(f'/proc/{pid}/environ').read_text().split('\0') if '=' in x};assert all(environment[k]==v for k,v in expected.items());assert expected['WF_TIER3_AUDIT_WAIT_STACK']=='1' and expected['WF_TIER3_MATRIX_DURATION']=='24h';assert 'TestFiveContainerMixedJournalLeaderEveryThirtySeconds' in parent['args'][1]
servers=json.loads((r/'actual-servers.json').read_text());assert len(servers)==5 and {s['node'] for s in servers}==set(range(5))
for s in servers:
 i=s['node'];assert sha(r/f'node-{i}-nats-server')==s['executable_sha256']=='751a788956b200d9ed08fa7dff4587b772b98e1b3e82cef6ff15b69be052f42d';assert 'github.com/nats-io/nats-server/v2' in s['build_info'];args=s['args'];prefix=s['name'].lstrip('/').rsplit('-n',1)[0];assert set(args[args.index('-routes')+1].split(','))=={f'nats://{prefix}-route-n{peer}:6222' for peer in range(5) if peer!=i};assert args[args.index('-cluster_advertise')+1]==f'{prefix}-route-n{i}:6222'
state=subprocess.check_output(['systemctl','--user','show','js-wf-watch-observed-journal-24h-20261005.service','-p','ActiveState','-p','MainPID','-p','MemoryMax','-p','RuntimeMaxUSec'],text=True);assert 'ActiveState=active' in state and f"MainPID={e['supervisor_pid']}" in state
watchstate=subprocess.check_output(['systemctl','--user','show','js-wf-watch-observed-journal-24h-sdk-watch-20261005.service','-p','ActiveState','-p','MainPID'],text=True);assert 'ActiveState=active' in watchstate
shutil.copy2('/tmp/js-wf-watch-observed-journal-24h-live-20261005.py',r/'executed-observer.py')
review={'observed_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'source':e['source'],'selected_git_inputs_verified':len(before['files']),'actual_sdk_pid':pid,'actual_sdk_sha256':b['sha256'],'actual_parent_environment_matches_profile':True,'actual_five_server_builds_and_route_arguments_verified':True,'unit_state':state,'sdk_observer_state':watchstate,'normal_2GiB_go_memory_budget':True,'original_24h_seed1_journal_profile':True,'added_watch_creation_cleanup_and_predeadline_stack_observation':True,'original_audit_and_recovery_gates_unchanged':True,'terminal_pass':False,'live_store_snapshot':False,'historical_cause_or_fix_confirmed':False,'qualifies_full_matrix_or_24h':False,'scope':'Immutable launch observation, not a final result. Parent SDK contains this row worker goroutines; child process stacks are excluded. Server processes verified at snapshot, not all future replacements.'}
(r/'independent-review.json').write_text(json.dumps(review,indent=2)+'\n');shutil.copy2(__file__,r/'executed-review.py')
for n in ['independent-review.json','review.json','executed-capture.py','executed-review.py','executed-observer.py','test-environment.json']:shutil.copy2(r/n,out/n)
shutil.copy2('/tmp/js-wf-preserve-read-proof-20261005.py',out/'executed-preserver.py');print(json.dumps(review))
