from pathlib import Path
import json,datetime,shutil,subprocess
repo=Path('/home/exedev/js-wf');base=repo/'docs/scale/tmp-storage-review-2026-10-06';out=base/'sixth-closed-roots'
reports=[json.loads(p.read_text()) for p in sorted(out.glob('*/offload.json'))]
ready=list(Path('/tmp/storage-sixth-proofs').glob('*/capture.json'))
assert len(reports)==len(ready), (len(reports),len(ready))
for p in out.glob('*/offload.json'):
 x=json.loads(p.read_text());links=json.loads((p.parent/'removed-links.json').read_text());files=json.loads((p.parent/'removed-files.json').read_text());meta=json.loads((p.parent/'archive-verification.json').read_text());inv=json.loads((p.parent/'fixture-inventory.json').read_text())
 assert len(links)==len(files)==len(set(v['path'] for v in links))
 assert set(v['path'] for v in links)==set(files)
 assert all(inv['files'][k]==v for k,v in files.items())
 assert x['allocated_bytes_removed']==sum(v['allocated_bytes'] for v in links if v['links_before_unlink']==1)
 assert x['verified_remote']==dict(bytes=meta['archive_bytes'],sha256=meta['archive_sha256'])
 assert not any((Path(x['root'])/k).exists() for k in files)
staging=json.loads((base/'sixth-verified-staging-removal/removal.json').read_text())['reports']
old=sum(r['allocated_bytes_removed'] for r in reports);oldstaging=sum(r['staging_bytes_removed'] for r in staging);createdstaging=sum(r['staging_bytes_removed'] for r in reports)
protected=['js-wf-bulk-journal-24h-joined-20261006','js-wf-bulk-latency-full400k-valid-20261006','js-wf-concurrent-state-400k-capacity-bounded-preparation-20261005','js-wf-timer-volume-million-service-20261001','js-wf-raft-callback-regression-20261006','js-wf-matrix-seed6-offline-bound-20261006','js-wf-lease-raft-offline-bound-20261006','js-wf-raft-safety170-20261006','js-wf-partition-seed6-candidate-20261006','js-wf-lease-partition-component-candidate-20261006']
assert all((Path('/tmp')/p).is_dir() for p in protected)
summary=dict(utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),uncounted_prior_partial_deletion_paths=sum(1 for p in out.glob('*/removed-links.json') for row in json.loads(p.read_text()) if row['links_before_unlink'] is None),closed_roots=len(reports),closed_root_allocated_bytes_reclaimed=old,redundant_preexisting_archives=len(staging),preexisting_archive_allocated_bytes_reclaimed=oldstaging,total_preexisting_allocated_bytes_reclaimed=old+oldstaging,new_capture_staging_bytes_removed_separately=createdstaging,available_bytes_observed=shutil.disk_usage('/tmp').free,protected_roots_retained=[str(Path('/tmp')/p) for p in protected],live_original_24h_sdk=Path('/proc/3461745').exists(),scope='Storage only. Full committed S3 archives verified before unlinking exact archived paths. Hard-link removals free allocated bytes only on final unlink; other aliases unchanged. Fresh visible closure checked with recorded process visibility limits. Protected fixtures, attachments, caches, system temporary files retained; no native gate promoted.')
(out/'summary.json').write_text(json.dumps(summary,indent=2)+'\n')
(out/'README.md').write_text(f"# Further closed temporary fixtures\n\nReclaimed at least **{(old+oldstaging)/2**30:.2f} GiB of pre-existing allocated storage** from {len(reports)} closed directories and {len(staging)} redundant archives. Newly created archive staging was removed separately and is excluded from this total. Observed free space: **{summary['available_bytes_observed']/2**30:.2f} GiB**; the live soak continues writing.\n\nComplete inventories were committed and pushed before S3 uploads. Full remote body readback receipts were committed and pushed before deletion. Removal additionally rechecked every remote archive member, metadata, inventory, current local file hash/mode/mtime, and visible process/descriptor/Docker/mount/loop closure. Small root logs/provenance and reviewer/model source remain local. Per-root records identify S3 objects and every removed path.\n\nHard-link aliases were unlinked without modifying remaining aliases. The reclaimed-byte total counts only observed final-link removals and excludes earlier partial deletions without retained link counts; per-path inode, device, prior link count and allocation are retained in removed-links.json. Full archives contain independent regular-file bodies for every captured path.\n\nThe original24h soak, both full400k donors, million-timer primary, latest Raft/candidate evidence, attachments, caches and system temporary directories remain local. Two disk-stall directories containing symlinks were skipped. Failed and interrupted test verdicts remain unchanged.\n\nRestore archives using `scripts/restore-fixture-archive.py` and the committed archive-verification.json and fixture-inventory.json to a fresh destination; native audits must operate on verified restored copies.\n")
readme=base/'README.md';text=readme.read_text().replace('Latest follow-up:', 'Previous follow-up:', 1);title,body=text.split('\n\n',1);marker='## Earlier cleanup';pos=text.index(marker)
text=title+"\n\n"+f"## Latest follow-up\n\nThis pass reclaimed **{(old+oldstaging)/2**30:.2f} GiB** from {len(reports)} additional closed directories and {len(staging)} redundant archives after full S3 verification. Observed free space is **{summary['available_bytes_observed']/2**30:.2f} GiB**. See [cleanup records](sixth-closed-roots/README.md) and [measured totals](sixth-closed-roots/summary.json). Hard-linked copies count toward reclaimed space only when the final link is removed.\n\n"+body
readme.write_text(text)
shutil.copyfile(__file__,out/'executed-summary-review.py')
print(json.dumps(summary,indent=2))
