from pathlib import Path
import json,hashlib,subprocess,shutil,base64,re,datetime
repo=Path('/home/exedev/js-wf');r=Path('/tmp/js-wf-ignored-effect-lease-loss-20261005');out=repo/'docs/scale/ignored-effect-lease-loss-2026-10-05';out.mkdir(parents=True,exist_ok=True)
def sha(p):
 with p.open('rb') as f:return hashlib.file_digest(f,'sha256').hexdigest()
def ns(s):
 m=re.fullmatch(r'(.*?)(?:\.(\d+))?Z',s);d=datetime.datetime.fromisoformat(m[1]).replace(tzinfo=datetime.timezone.utc);return int(d.timestamp())*10**9+int((m[2] or '').ljust(9,'0'))
e=json.load(open(r/'execution.json'));b=json.load(open(r/'binary.json'));assert e['status']=='passed' and e['exit_code']==0 and not Path(f"/proc/{e['pid']}").exists();assert sha(r/'integration.test')==e['sha256']==b['sha256'] and e['build_info'].splitlines()[1:]==b['build_info'].splitlines()[1:];assert '-race=true' in b['build_info'] and 'vcs.modified=false' in b['build_info'] and 'vcs.revision='+e['source'] in b['build_info'] and 'github.com/nats-io/nats-server/v2\tv2.15.0' in b['build_info']
before=json.load(open(r/'source-before.json'));assert before==json.load(open(r/'source-after.json')) and before['revision']==e['source']
for n,d in before['files'].items():assert sha(r/'source'/n)==d==hashlib.sha256(subprocess.check_output(['git','show',e['source']+':'+n],cwd=repo)).hexdigest()
external=json.load(open(r/'external-source-before.json'));assert external==json.load(open(r/'external-source-after.json'));paths=json.load(open(r/'external-captured-paths.json'));assert set(paths)==set(external)
for n,d in external.items():assert sha(r/paths[n])==d
p=next((r/'originals').rglob('blocked-effect-proof.json'));proof=json.load(open(p));assert proof['ignores_cancellation'] and not proof['native_test_failed'] and proof['abandoned_effect_blocked_through_successor_terminal'] and proof['all_three_peer_journals_and_results_unchanged_after_stale_result'];assert proof['effects']==2 and proof['committed_lease_revision']==5>proof['initial_lease_revision']==4 and proof['committed_lease_value']=={'worker':'lost-renew-first','epoch':1}
partial=proof['partial_journal'];records=proof['successor_journal'];assert partial==records[:2] and [x['kind'] for x in records]==['Started','StepRequested','StepCompleted','Completed'] and [x['index'] for x in records]==list(range(4)) and [x['sequence'] for x in records]==list(range(1,5));assert [x['epoch'] for x in records]==[1,1,7,7] and [x['worker_id'] for x in records]==['lost-renew-first']*2+['lost-renew-second']*2;assert records[1]['payload']['input_hash']==hashlib.sha256(b'0').hexdigest() and records[2]['payload']['result']==42 and base64.b64decode(records[3]['payload']['result'],validate=True)==b'42' and records[3]['payload']['inv_seq']==1
assert proof['integrity_report']=={'Invocations':1,'Journals':1,'Entries':4,'Terminal':1};assert proof['lease_stream_info']['config']['max_age']==12_000_000_000 and proof['lease_stream_info']['config']['num_replicas']==3 and proof['lease_stream_info']['config']['storage']=='file';assert proof['dispatch_consumer_info']['config']['ack_wait']==13_000_000_000 and proof['dispatch_consumer_info']['num_pending']==proof['dispatch_consumer_info']['num_ack_pending']==0 and proof['first_worker_metrics']['fencing_events']==1
assert ns(proof['fence_observed'])<ns(proof['first_worker_stopped'])<ns(proof['successor_terminal_observed'])<ns(proof['effect_released'])<ns(proof['abandoned_effect_returned']);measured=ns(proof['successor_terminal_observed'])-ns(proof['fence_observed']);assert 0<measured<=proof['recovery_from_observed_fence_ns']<30_000_000_000 and proof['recovery_from_observed_fence_ns']-measured<1_000_000
traffic=json.load(open(p.parent/'proxy-traffic.json'));assert not traffic['truncated'] and len(traffic['connections'])==2 and {f['connection'] for f in traffic['frames']}=={c['id'] for c in traffic['connections']}
streams={direction:b''.join(base64.b64decode(f['data'],validate=True) for f in traffic['frames'] if f['direction']==direction) for direction in ['client_to_server','server_to_client']};assert b'Nats-Expected-Last-Subject-Sequence: 4' in streams['client_to_server'] and b'$KV.WF_LEASE.heartbeat.lost-renew-handoff' in streams['client_to_server'];pubacks=[json.loads(x) for x in re.findall(rb'\{[^{}\r\n]*"stream":"KV_WF_LEASE"[^{}\r\n]*\}',streams['server_to_client'])];assert [x['seq'] for x in pubacks]==[1,2,3,4,6] and all(x['seq']!=proof['committed_lease_revision'] for x in pubacks)
assert all((p.parent/'cluster'/f'node-{i}').is_dir() for i in range(3));log=(r/'native.log').read_text();assert 'PASS' in log and 'FAIL' not in log and 'WARNING: DATA RACE' not in log
review={'source':e['source'],'actual_sdk_sha256':e['sha256'],'selected_git_inputs_verified':len(before['files']),'selected_external_go_cgo_test_inputs_verified':len(external),'input_inventory_not_exhaustive_race_assembly_embed_compiler_provenance':True,'native_R3_servers_embedded_in_actual_sdk':True,'separate_server_process_hashes':False,'native_race_pass_seconds':14.96,'recovery_from_observed_fence_ns':proof['recovery_from_observed_fence_ns'],'old_epoch':1,'successor_epoch':7,'effects':2,'retained_journal_entries':4,'terminal_records':1,'independent_terminal_bytes':'42','proxy_forwarded_lease_puback_sequences':[x['seq'] for x in pubacks],'committed_renewal_puback_absent_from_forwarded_trace':True,'all_three_peer_post_stale_result_assertions_passed':True,'production_decisions_or_timing_changed':False,'qualifies_native_sdk_effect_ignoring_cancellation_under_lease_loss':True,'qualifies_raw_handler_blocking_outside_sdk_effects':False,'qualifies_full_matrix_or_24h':False,'historical_server_cause_confirmed':False,'limitations':['The abandoned external effect can continue; downstream idempotency remains required.','No worker process SIGKILL, Raft partition, independent stopped-store reopen or physical replica drain qualification.','Three embedded native server instances have file stores; no separate server executable processes or server logs (NoLog fixture).','Dispatch drain and all-peer invariants have captured named-test assertion scope.','First worker handoff enqueue count0: confirmed local recovery here uses NAK/redelivery, not durable handoff enqueue coverage.','Shares VM with live million candidate and actual24h diagnostic; no pressure cause inferred.']}
(r/'independent-review.json').write_text(json.dumps(review,indent=2)+'\n');shutil.copy2(__file__,r/'executed-review.py')
for n in ['execution.json','independent-review.json','executed-review.py','executed-producer.py']:shutil.copy2(r/n,out/n)
shutil.copy2(p,out/p.name);shutil.copy2('/tmp/js-wf-preserve-read-proof-20261005.py',out/'executed-preserver.py');print(json.dumps(review))
