package worker

import (
	"context"
	"encoding/json"
	"errors"
	"strings"
	"testing"
	"time"

	"github.com/nats-io/nats.go/jetstream"
	"js-wf/client"
	"js-wf/identity"
	"js-wf/journal"
	"js-wf/lease"
	"js-wf/provision"
	"js-wf/reconcile"
	"js-wf/testcluster"
	"js-wf/wf"
)

// Internal migration control: public continuation admission remains closed.
// Every checkpoint here is generated by the production SDK and delivery path.
func TestNativeGraphContinuationSDKFlow(t *testing.T) {
	for _, domain := range []string{"", "WFCONTINUATIONSDK"} {
		name := "R1"
		if domain != "" {
			name = "R3Domain"
		}
		t.Run(name, func(t *testing.T) { testNativeGraphContinuationSDKFlow(t, domain, false, false, false, false) })
	}
}
func TestNativeGraphContinuationSDKPartitionFlow(t *testing.T) {
	for _, domain := range []string{"", "WFCONTINUATIONSDK"} {
		name := "R1"
		if domain != "" {
			name = "R3Domain"
		}
		t.Run(name, func(t *testing.T) { testNativeGraphContinuationSDKFlow(t, domain, true, false, false, false) })
	}
}
func TestNativeGraphContinuationBufferedSignals(t *testing.T) {
	for _, domain := range []string{"", "WFCONTINUATIONSDK"} {
		name := "R1"
		if domain != "" {
			name = "R3Domain"
		}
		t.Run(name, func(t *testing.T) { testNativeGraphContinuationSDKFlow(t, domain, false, true, false, false) })
	}
}
func TestNativeGraphContinuationChildPromise(t *testing.T) {
	for _, domain := range []string{"", "WFCONTINUATIONSDK"} {
		name := "R1"
		if domain != "" {
			name = "R3Domain"
		}
		t.Run(name, func(t *testing.T) { testNativeGraphContinuationSDKFlow(t, domain, false, false, true, false) })
	}
}
func TestNativeGraphContinuationBufferedChildPromise(t *testing.T) {
	for _, domain := range []string{"", "WFCONTINUATIONSDK"} {
		name := "R1"
		if domain != "" {
			name = "R3Domain"
		}
		t.Run(name, func(t *testing.T) { testNativeGraphContinuationSDKFlow(t, domain, false, false, true, true) })
	}
}
func testNativeGraphContinuationSDKFlow(t *testing.T, domain string, partition, bufferedSignals, childPromiseFlow, bufferedChild bool) {
	replicas := 1
	if domain != "" {
		replicas = 3
	}
	var cluster *testcluster.Cluster
	var err error
	if domain == "" {
		cluster, err = testcluster.Start(t.TempDir(), replicas)
	} else {
		cluster, err = testcluster.StartWithDomain(t.TempDir(), replicas, domain)
	}
	if err != nil {
		t.Fatal(err)
	}
	defer cluster.Close()
	timeout := 30 * time.Second
	if childPromiseFlow {
		timeout = time.Minute
	}
	ctx, cancel := context.WithTimeout(context.Background(), timeout)
	defer cancel()
	if replicas > 1 {
		for ctx.Err() == nil {
			ready := false
			for _, server := range cluster.Servers {
				ready = ready || server.JetStreamIsLeader() && len(server.JetStreamClusterPeers()) == replicas
			}
			if ready {
				break
			}
			time.Sleep(20 * time.Millisecond)
		}
	}
	var js jetstream.JetStream
	if domain == "" {
		js, err = jetstream.New(cluster.Clients[0])
	} else {
		js, err = jetstream.NewWithDomain(cluster.Clients[0], domain)
	}
	if err != nil {
		t.Fatal(err)
	}
	if err := provision.Ensure(ctx, js, replicas); err != nil {
		t.Fatal(err)
	}
	cfg := journal.NativeGraphConfig{AuthorityStream: "SDKCONT_AUTH", AuthorityPrefix: "wf.graph.sdkcontinue", ObjectBucket: "SDKCONT_OBJECTS", ExpectedReplicas: replicas, CanonicalStarts: true, CanonicalSignals: true, CheckpointIndex: true}
	configs, err := journal.NativeGraphStreamConfigs(cfg, replicas)
	if err != nil {
		t.Fatal(err)
	}
	for _, config := range configs {
		if _, err := js.CreateStream(ctx, config); err != nil {
			t.Fatal(err)
		}
	}
	graph, err := journal.OpenNativeGraphStore(ctx, js, cfg)
	if err != nil {
		t.Fatal(err)
	}
	c, err := client.New(js).WithGraphJournal(graph)
	if err != nil {
		t.Fatal(err)
	}
	h, err := c.Start(ctx, "test", "sdkcontinue", []byte(`7`))
	if err != nil {
		t.Fatal(err)
	}
	if bufferedSignals {
		if _, err := c.Signal(ctx, h.Type, h.ID, "go", []byte(`11`), "go"); err != nil {
			t.Fatal(err)
		}
	}
	calls, effects := map[string]int{}, 0
	var childPromise wf.Promise
	childCalls := 0
	childResult := strings.Repeat("child", 140000)
	checkPromise := func(c *wf.Context, locals json.RawMessage, count int) error {
		var data struct {
			Count   int        `json:"count"`
			Promise wf.Promise `json:"promise"`
		}
		if json.Unmarshal(locals, &data) != nil || data.Count != count {
			return wf.ErrCorruptJournal
		}
		raw, err := wf.AwaitPromise(c, data.Promise)
		if err != nil {
			return err
		}
		var result string
		if json.Unmarshal(raw, &result) != nil || result != childResult {
			return wf.ErrCorruptJournal
		}
		return nil
	}
	initial := func(c *wf.Context, input json.RawMessage) (json.RawMessage, error) {
		calls["initial"]++
		if string(input) != "7" {
			return nil, wf.ErrCorruptJournal
		}
		got, err := wf.RunOnce(c, "initial-once", nil, func(context.Context, string) (int, error) { effects++; return 42, nil })
		if err != nil {
			return nil, err
		}
		if err := c.SetState("value", got); err != nil {
			return nil, err
		}
		if childPromiseFlow {
			var err error
			childPromise, err = wf.CallAsync(c, "testchild", []byte(`7`))
			if err != nil {
				return nil, err
			}
			return nil, wf.Continue(c, "next", map[string]any{"count": 1, "promise": childPromise})
		}
		return nil, wf.Continue(c, "next", map[string]int{"count": 1})
	}
	handlers := map[string]Handler{h.Type: initial}
	if childPromiseFlow {
		handlers["testchild"] = func(*wf.Context, json.RawMessage) (json.RawMessage, error) {
			childCalls++
			return json.Marshal(childResult)
		}
	}
	runner, err := New(ctx, js, "sdkcontinue", handlers, WithGraphJournal(graph))
	if err != nil {
		t.Fatal(err)
	}
	defer func() {
		if err := runner.Close(); err != nil {
			t.Error(err)
		}
	}()
	runner.continuations = map[string]map[string]ContinuationHandler{h.Type: {
		"next": func(c *wf.Context, input, locals json.RawMessage) (json.RawMessage, error) {
			calls["next"]++
			var nextPromise wf.Promise
			if childPromiseFlow {
				var data struct {
					Count   int        `json:"count"`
					Promise wf.Promise `json:"promise"`
				}
				if json.Unmarshal(locals, &data) != nil || data.Count != 1 {
					return nil, wf.ErrCorruptJournal
				}
				nextPromise = data.Promise
			}
			if childPromiseFlow && !bufferedChild {
				if err := checkPromise(c, locals, 1); err != nil {
					return nil, err
				}
			}
			if bufferedSignals {
				data, err := wf.AwaitSignal(c, "go")
				if err != nil || string(data) != "11" {
					return nil, wf.ErrCorruptJournal
				}
			}
			if string(input) != "7" || !childPromiseFlow && string(locals) != `{"count":1}` {
				return nil, wf.ErrCorruptJournal
			}
			var value int
			ok, err := c.GetState("value", &value)
			if err != nil || !ok || value != 42 {
				return nil, wf.ErrCorruptJournal
			}
			result, err := wf.RunOnce(c, "next-once", nil, func(context.Context, string) (int, error) { effects++; return value + 1, nil })
			if err != nil {
				return nil, err
			}
			if err := c.SetState("value", result); err != nil {
				return nil, err
			}
			if childPromiseFlow {
				return nil, wf.Continue(c, "finish", map[string]any{"count": 2, "promise": nextPromise})
			}
			return nil, wf.Continue(c, "finish", map[string]int{"count": 2})
		},
		"finish": func(c *wf.Context, input, locals json.RawMessage) (json.RawMessage, error) {
			calls["finish"]++
			if childPromiseFlow {
				if err := checkPromise(c, locals, 2); err != nil {
					return nil, err
				}
			}
			if bufferedSignals {
				data, err := wf.AwaitSignal(c, "later")
				if err != nil || string(data) != "13" {
					return nil, wf.ErrCorruptJournal
				}
			}
			if string(input) != "7" || !childPromiseFlow && string(locals) != `{"count":2}` {
				return nil, wf.ErrCorruptJournal
			}
			var value int
			ok, err := c.GetState("value", &value)
			if err != nil || !ok || value != 43 {
				return nil, wf.ErrCorruptJournal
			}
			return json.Marshal(value)
		},
	}}
	leases, err := lease.New(ctx, js)
	if err != nil {
		t.Fatal(err)
	}
	execute := func() {
		t.Helper()
		owner, err := leases.Acquire(ctx, h.Type, h.ID, "sdkcontinue")
		if err != nil {
			t.Fatal(err)
		}
		var noOp bool
		err = runner.execute(ctx, h.Type, h.ID, owner, time.Time{}, timerWakeup{}, &noOp, nil)
		releaseErr := owner.Release(ctx)
		if err != nil || releaseErr != nil {
			t.Fatal("SDK stage delivery", err, releaseErr)
		}
	}
	scan, err := reconcile.NewCanonicalContinuationScan(js, graph)
	if err != nil {
		t.Fatal(err)
	}
	runs, err := js.Stream(ctx, "WF_RUN")
	if err != nil {
		t.Fatal(err)
	}
	if partition {
		runCtx, stop := context.WithCancel(ctx)
		done := make(chan error, 1)
		go func() { done <- runner.RunPartition(runCtx, identity.Partition(h.Type, h.ID, provision.Partitions)) }()
		_, awaitErr := c.Await(ctx, h.Type, h.ID)
		stop()
		runErr := <-done
		if awaitErr != nil || runErr != nil && !errors.Is(runErr, context.Canceled) {
			t.Fatal("partition SDK flow", awaitErr, runErr)
		}
	} else {
		for _, stage := range []string{"next", "finish"} {
			execute()
			status, err := graph.InspectStart(ctx, h.Type, h.ID)
			if err != nil || status.Checkpoint == nil || status.Checkpoint.Stage != stage || !status.ContinuationReady() {
				t.Fatal("SDK did not publish checkpoint", stage, status, err)
			}
			if err := runs.Purge(ctx); err != nil {
				t.Fatal(err)
			}
			budget := 1
			if childPromiseFlow {
				budget = 4
			}
			result, err := scan.Scan(ctx, 1, budget, false)
			if err != nil || result.Reenqueued != 1 {
				t.Fatal("SDK boundary wakeup not recovered", stage, result, err)
			}
			if childPromiseFlow {
				if stage == "next" {
					owner, err := leases.Acquire(ctx, childPromise.ChildType, childPromise.ChildID, "sdkchild")
					if err != nil {
						t.Fatal(err)
					}
					var noOp bool
					err = runner.execute(ctx, childPromise.ChildType, childPromise.ChildID, owner, time.Time{}, timerWakeup{}, &noOp, nil)
					releaseErr := owner.Release(ctx)
					if err != nil || releaseErr != nil {
						t.Fatal("child delivery", err, releaseErr)
					}
				} else {
					retired, err := graph.InspectRetirement(ctx, childPromise.ChildType, childPromise.ChildID)
					if err != nil {
						t.Fatal(err)
					}
					if err := graph.Retire(ctx, childPromise.ChildType, childPromise.ChildID, retired.Invocation, retired.Tail); err != nil {
						t.Fatal(err)
					}
				}
			}
			if bufferedSignals && stage == "next" {
				if _, err := c.Signal(ctx, h.Type, h.ID, "later", []byte(`13`), "later"); err != nil {
					t.Fatal(err)
				}
			}
		}
		execute()
	}
	execute() // Completion followed by an independently fenced duplicate.
	result, err := c.Await(ctx, h.Type, h.ID)
	if err != nil || string(result) != "43" || effects != 2 || calls["initial"] != 1 || calls["next"] != 1 || calls["finish"] != 1 {
		t.Fatal("SDK workflow replay/result", string(result), err, calls, effects)
	}
	records, _, err := graph.ReadExisting(ctx, h.Type, h.ID, h.InvSeq)
	if err != nil {
		t.Fatal(err)
	}
	completions := 0
	for i, record := range records {
		if record.Index != uint64(i) {
			t.Fatal("absolute journal index changed", record)
		}
		if record.Kind == journal.Completed {
			completions++
		}
	}
	if completions != 1 {
		t.Fatal("terminal append repeated", completions)
	}
	legacy, err := js.Stream(ctx, "WF_JRN")
	if err != nil {
		t.Fatal(err)
	}
	info, err := legacy.Info(ctx)
	if err != nil || info.State.Msgs != 0 {
		t.Fatal("SDK flow wrote legacy journal", info, err)
	}
	if childPromiseFlow && childCalls != 1 {
		t.Fatal("child was replayed", childCalls)
	}
	t.Logf("SDK initial/next/finish=%v effects=%d records=%d result=%s", calls, effects, len(records), result)
}
