package worker

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"strings"
	"sync/atomic"
	"testing"
	"time"

	"github.com/nats-io/nats.go/jetstream"
	"js-wf/client"
	"js-wf/identity"
	"js-wf/integrity"
	"js-wf/internal/checkpoint"
	"js-wf/internal/graphpublication"
	"js-wf/internal/retainedgraph"
	"js-wf/journal"
	"js-wf/lease"
	"js-wf/provision"
	"js-wf/reconcile"
	"js-wf/testcluster"
	"js-wf/wf"
	"os"
)

// Internal migration control: public continuation admission remains closed.
// Every checkpoint here is generated by the production SDK and delivery path.
func TestNativeGraphContinuationSDKFlow(t *testing.T) {
	for _, domain := range []string{"", "WFCONTINUATIONSDK"} {
		name := "R1"
		if domain != "" {
			name = "R3Domain"
		}
		t.Run(name, func(t *testing.T) { testNativeGraphContinuationSDKFlow(t, domain, false, false, false, false) })
	}
}
func TestNativeGraphContinuationTimerHistory(t *testing.T) {
	for _, domain := range []string{"", "WFCONTINUATIONSDK"} {
		name := "R1"
		if domain != "" {
			name = "R3Domain"
		}
		for _, archive := range []bool{false, true} {
			t.Run(fmt.Sprintf("%s/archive=%t", name, archive), func(t *testing.T) {
				testNativeGraphContinuationSDKFlow(t, domain, false, false, false, false, archive, false, false, false, false, false, true)
			})
		}
	}
}
func TestNativeGraphContinuationCancelledTimerWakeup(t *testing.T) {
	for _, domain := range []string{"", "WFCONTINUATIONSDK"} {
		name := "R1"
		if domain != "" {
			name = "R3Domain"
		}
		t.Run(name, func(t *testing.T) {
			testNativeGraphContinuationSDKFlow(t, domain, false, false, false, false, true, false, false, false, false, false, true, false, true)
		})
	}
}
func TestNativeGraphContinuationScheduledTimerFlow(t *testing.T) {
	for _, domain := range []string{"", "WFCONTINUATIONSDK"} {
		name := "R1"
		if domain != "" {
			name = "R3Domain"
		}
		t.Run(name, func(t *testing.T) {
			testNativeGraphContinuationSDKFlow(t, domain, true, false, false, false, false, false, false, false, false, false, true, true)
		})
	}
}
func TestNativeGraphContinuationSDKPartitionFlow(t *testing.T) {
	for _, domain := range []string{"", "WFCONTINUATIONSDK"} {
		name := "R1"
		if domain != "" {
			name = "R3Domain"
		}
		t.Run(name, func(t *testing.T) { testNativeGraphContinuationSDKFlow(t, domain, true, false, false, false) })
	}
}
func TestNativeGraphContinuationBufferedSignals(t *testing.T) {
	for _, domain := range []string{"", "WFCONTINUATIONSDK"} {
		name := "R1"
		if domain != "" {
			name = "R3Domain"
		}
		t.Run(name, func(t *testing.T) { testNativeGraphContinuationSDKFlow(t, domain, false, true, false, false) })
	}
}
func TestNativeGraphContinuationChildPromise(t *testing.T) {
	for _, domain := range []string{"", "WFCONTINUATIONSDK"} {
		name := "R1"
		if domain != "" {
			name = "R3Domain"
		}
		t.Run(name, func(t *testing.T) { testNativeGraphContinuationSDKFlow(t, domain, false, false, true, false) })
	}
}
func TestNativeGraphContinuationBufferedChildPromise(t *testing.T) {
	for _, domain := range []string{"", "WFCONTINUATIONSDK"} {
		name := "R1"
		if domain != "" {
			name = "R3Domain"
		}
		t.Run(name, func(t *testing.T) { testNativeGraphContinuationSDKFlow(t, domain, false, false, true, true) })
	}
}

func TestNativeGraphContinuationFailedChildPromise(t *testing.T) {
	for _, domain := range []string{"", "WFCONTINUATIONSDK"} {
		for _, archive := range []bool{false, true} {
			for _, buffered := range []bool{false, true} {
				name := "R1"
				if domain != "" {
					name = "R3Domain"
				}
				t.Run(fmt.Sprintf("%s/archive=%t/buffered=%t", name, archive, buffered), func(t *testing.T) {
					testNativeGraphContinuationSDKFlow(t, domain, false, false, true, buffered, archive, true)
				})
			}
		}
	}
}

func TestNativeGraphContinuationPendingChildAcrossCheckpoints(t *testing.T) {
	for _, domain := range []string{"", "WFCONTINUATIONSDK"} {
		for _, archive := range []bool{false, true} {
			for _, failed := range []bool{false, true} {
				name := "R1"
				if domain != "" {
					name = "R3Domain"
				}
				t.Run(fmt.Sprintf("%s/archive=%t/failed=%t", name, archive, failed), func(t *testing.T) {
					// Carry an unresolved promise through both checkpoints, then
					// actually suspend the final stage before executing the child.
					testNativeGraphContinuationSDKFlow(t, domain, false, false, true, true, archive, failed, true)
				})
			}
		}
	}
}

func TestNativeGraphContinuationCancelPendingChild(t *testing.T) {
	for _, domain := range []string{"", "WFCONTINUATIONSDK"} {
		for _, archive := range []bool{false, true} {
			for _, failed := range []bool{false, true} {
				name := "R1"
				if domain != "" {
					name = "R3Domain"
				}
				t.Run(fmt.Sprintf("%s/archive=%t/failed=%t", name, archive, failed), func(t *testing.T) {
					testNativeGraphContinuationSDKFlow(t, domain, false, false, true, true, archive, failed, true, true)
				})
			}
		}
	}
}

func TestNativeGraphContinuationCancelRunningEffect(t *testing.T) {
	for _, domain := range []string{"", "WFCONTINUATIONSDK"} {
		for _, archive := range []bool{false, true} {
			for _, lateSuccess := range []bool{false, true} {
				name := "R1"
				if domain != "" {
					name = "R3Domain"
				}
				t.Run(fmt.Sprintf("%s/archive=%t/late-success=%t", name, archive, lateSuccess), func(t *testing.T) {
					testNativeGraphContinuationSDKFlow(t, domain, false, false, false, false, archive, false, false, false, true, lateSuccess)
				})
			}
		}
	}
}

func TestNativeGraphContinuationArchiveCollection(t *testing.T) {
	for _, domain := range []string{"", "WFCONTINUATIONSDK"} {
		for _, mode := range []string{"state", "signals", "child", "buffered-child"} {
			name := "R1/" + mode
			if domain != "" {
				name = "R3Domain/" + mode
			}
			t.Run(name, func(t *testing.T) {
				testNativeGraphContinuationSDKFlow(t, domain, false, mode == "signals", mode == "child" || mode == "buffered-child", mode == "buffered-child", true)
			})
		}
	}
}
func testNativeGraphContinuationSDKFlow(t *testing.T, domain string, partition, bufferedSignals, childPromiseFlow, bufferedChild bool, archiveMode ...bool) {
	// Optional modes: archive, failed child, pending child, cancel pending parent, running effect cancellation, late success, timer history, positive timer wakeup, cancelled timer wakeup.
	archive := len(archiveMode) != 0 && archiveMode[0]
	childFailure := len(archiveMode) > 1 && archiveMode[1]
	pendingChild := len(archiveMode) > 2 && archiveMode[2]
	cancelPendingChild := len(archiveMode) > 3 && archiveMode[3]
	cancelRunningEffect := len(archiveMode) > 4 && archiveMode[4]
	lateEffectSuccess := len(archiveMode) > 5 && archiveMode[5]
	timerHistory := len(archiveMode) > 6 && archiveMode[6]
	positiveTimer := len(archiveMode) > 7 && archiveMode[7]
	cancelledWakeup := len(archiveMode) > 8 && archiveMode[8]
	effectEntered := make(chan struct{})
	if cancelPendingChild && !pendingChild {
		t.Fatal("cancellation fixture requires an unresolved child")
	}
	if pendingChild && (!childPromiseFlow || !bufferedChild || partition) {
		t.Fatal("pending-child fixture requires direct deliveries and a carried promise")
	}
	replicas := 1
	if domain != "" {
		replicas = 3
	}
	var cluster *testcluster.Cluster
	var err error
	clusterRoot := t.TempDir()
	if base := os.Getenv("WF_GRAPH_SDK_DIAGNOSTIC_ROOT"); base != "" {
		if err = os.MkdirAll(base, 0700); err != nil {
			t.Fatal(err)
		}
		clusterRoot, err = os.MkdirTemp(base, "native-")
		if err != nil {
			t.Fatal(err)
		}
		t.Logf("SDK_DIAGNOSTIC_STORE test=%s root=%s", t.Name(), clusterRoot)
	}
	if domain == "" {
		cluster, err = testcluster.Start(clusterRoot, replicas)
	} else {
		cluster, err = testcluster.StartWithDomain(clusterRoot, replicas, domain)
	}
	if err != nil {
		t.Fatal(err)
	}
	defer cluster.Close()
	timeout := 30 * time.Second
	if childPromiseFlow || archive {
		timeout = time.Minute
	}
	if childFailure && archive || pendingChild || cancelRunningEffect {
		// Functional watchdog for the complete multi-delivery/collection fixture.
		// Recovery latency is checked separately from kill through exact ACK.
		timeout = 2 * time.Minute
	}
	ctx, cancel := context.WithTimeout(context.Background(), timeout)
	defer cancel()
	phaseStart := time.Now()
	var requests atomic.Int64
	phase := func(name string) {
		t.Helper()
		t.Logf("SDK_PHASE name=%s elapsed=%s remaining=%s sdk_requests=%d", name, time.Since(phaseStart), time.Until(phaseStart.Add(timeout)), requests.Load())
	}
	defer phase("finished")
	if replicas > 1 {
		for ctx.Err() == nil {
			ready := false
			for _, server := range cluster.Servers {
				ready = ready || server.JetStreamIsLeader() && len(server.JetStreamClusterPeers()) == replicas
			}
			if ready {
				break
			}
			time.Sleep(20 * time.Millisecond)
		}
	}
	var js jetstream.JetStream
	trace := jetstream.WithClientTrace(&jetstream.ClientTrace{RequestSent: func(string, []byte) { requests.Add(1) }})
	if domain == "" {
		js, err = jetstream.New(cluster.Clients[0], trace)
	} else {
		js, err = jetstream.NewWithDomain(cluster.Clients[0], domain, trace)
	}
	if err != nil {
		t.Fatal(err)
	}
	if err := provision.Ensure(ctx, js, replicas); err != nil {
		t.Fatal(err)
	}
	cfg := journal.NativeGraphConfig{AuthorityStream: "SDKCONT_AUTH", AuthorityPrefix: "wf.graph.sdkcontinue", ObjectBucket: "SDKCONT_OBJECTS", ExpectedReplicas: replicas, CanonicalStarts: true, CanonicalSignals: true, CheckpointIndex: true, ArchiveCheckpoints: archive}
	configs, err := journal.NativeGraphStreamConfigs(cfg, replicas)
	if err != nil {
		t.Fatal(err)
	}
	for _, config := range configs {
		if _, err := js.CreateStream(ctx, config); err != nil {
			t.Fatal(err)
		}
	}
	graph, err := journal.OpenNativeGraphStore(ctx, js, cfg)
	if err != nil {
		t.Fatal(err)
	}
	c, err := client.New(js).WithGraphJournal(graph)
	if err != nil {
		t.Fatal(err)
	}
	h, err := c.Start(ctx, "test", "sdkcontinue", []byte(`7`))
	if err != nil {
		t.Fatal(err)
	}
	if bufferedSignals {
		if _, err := c.Signal(ctx, h.Type, h.ID, "go", []byte(`11`), "go"); err != nil {
			t.Fatal(err)
		}
	}
	calls, effects := map[string]int{}, 0
	var childPromise wf.Promise
	childCalls := 0
	var pendingPrefix []journal.Record
	childResult := strings.Repeat("child", 140000)
	checkPromise := func(c *wf.Context, locals json.RawMessage, count int) error {
		var data struct {
			Count   int        `json:"count"`
			Promise wf.Promise `json:"promise"`
		}
		if json.Unmarshal(locals, &data) != nil || data.Count != count {
			return wf.ErrCorruptJournal
		}
		raw, err := wf.AwaitPromise(c, data.Promise)
		if childFailure {
			if err == nil || err.Error() != "planned child failure" || len(raw) != 0 {
				return wf.ErrCorruptJournal
			}
			return nil
		}
		if err != nil {
			return err
		}
		var result string
		if json.Unmarshal(raw, &result) != nil || result != childResult {
			return wf.ErrCorruptJournal
		}
		return nil
	}
	initial := func(c *wf.Context, input json.RawMessage) (json.RawMessage, error) {
		calls["initial"]++
		if string(input) != "7" {
			return nil, wf.ErrCorruptJournal
		}
		got, err := wf.RunOnce(c, "initial-once", nil, func(context.Context, string) (int, error) { effects++; return 42, nil })
		if err != nil {
			return nil, err
		}
		if err := c.SetState("value", got); err != nil {
			return nil, err
		}
		if timerHistory {
			cancelled, err := c.Timer("initial-cancel", time.Hour)
			if err != nil {
				return nil, err
			}
			if err = cancelled.Cancel(); err != nil {
				return nil, err
			}
			duration := time.Duration(0)
			if positiveTimer {
				duration = 75 * time.Millisecond
			}
			fired, err := c.Timer("initial-fire", duration)
			if err != nil {
				return nil, err
			}
			if err = fired.Await(); err != nil {
				return nil, err
			}
		}
		if childPromiseFlow {
			var err error
			childPromise, err = wf.CallAsync(c, "testchild", []byte(`7`))
			if err != nil {
				return nil, err
			}
			return nil, wf.Continue(c, "next", map[string]any{"count": 1, "promise": childPromise})
		}
		return nil, wf.Continue(c, "next", map[string]int{"count": 1})
	}
	handlers := map[string]Handler{h.Type: initial}
	if childPromiseFlow {
		handlers["testchild"] = func(*wf.Context, json.RawMessage) (json.RawMessage, error) {
			childCalls++
			if childFailure {
				return nil, errors.New("planned child failure")
			}
			return json.Marshal(childResult)
		}
	}
	var observe func(OperationEvent)
	if childFailure || pendingChild {
		observe = func(event OperationEvent) {
			if event.Operation == "journal_append" || event.Error != "" {
				t.Logf("SDK_OPERATION op=%s type=%s index=%d kind=%s duration=%s error=%q sdk_requests=%d", event.Operation, event.Type, event.JournalIndex, event.JournalKind, event.Duration, event.Error, requests.Load())
			}
		}
	}
	runner, err := New(ctx, js, "sdkcontinue", handlers, WithGraphJournal(graph), WithOperationObserver(observe))
	if err != nil {
		t.Fatal(err)
	}
	defer func() {
		if err := runner.Close(); err != nil {
			t.Error(err)
		}
	}()
	runner.continuations = map[string]map[string]ContinuationHandler{h.Type: {
		"next": func(c *wf.Context, input, locals json.RawMessage) (json.RawMessage, error) {
			calls["next"]++
			if timerHistory {
				cancelled, err := c.Timer("next-cancel", time.Hour)
				if err != nil {
					return nil, err
				}
				if err = cancelled.Cancel(); err != nil {
					return nil, err
				}
				selected, err := c.Timer("selected-fire", 0)
				if err != nil {
					return nil, err
				}
				branch, _, err := selected.SelectSignal("absent")
				if err != nil || branch != wf.TimerSelected {
					return nil, fmt.Errorf("timer branch: %s %w", branch, err)
				}
				many, err := c.Timer("many-fire", 0)
				if err != nil {
					return nil, err
				}
				index, _, err := wf.Select(c, many)
				if err != nil || index != 0 {
					return nil, fmt.Errorf("timer select: %d %w", index, err)
				}
			}
			var nextPromise wf.Promise
			if childPromiseFlow {
				var data struct {
					Count   int        `json:"count"`
					Promise wf.Promise `json:"promise"`
				}
				if json.Unmarshal(locals, &data) != nil || data.Count != 1 {
					return nil, wf.ErrCorruptJournal
				}
				nextPromise = data.Promise
			}
			if childPromiseFlow && !bufferedChild {
				if err := checkPromise(c, locals, 1); err != nil {
					return nil, err
				}
			}
			if bufferedSignals {
				data, err := wf.AwaitSignal(c, "go")
				if err != nil || string(data) != "11" {
					return nil, wf.ErrCorruptJournal
				}
			}
			if string(input) != "7" || !childPromiseFlow && string(locals) != `{"count":1}` {
				return nil, wf.ErrCorruptJournal
			}
			var value int
			ok, err := c.GetState("value", &value)
			if err != nil || !ok || value != 42 {
				return nil, wf.ErrCorruptJournal
			}
			result, err := wf.RunOnce(c, "next-once", nil, func(context.Context, string) (int, error) { effects++; return value + 1, nil })
			if err != nil {
				return nil, err
			}
			if err := c.SetState("value", result); err != nil {
				return nil, err
			}
			if childPromiseFlow {
				return nil, wf.Continue(c, "finish", map[string]any{"count": 2, "promise": nextPromise})
			}
			return nil, wf.Continue(c, "finish", map[string]int{"count": 2})
		},
		"finish": func(c *wf.Context, input, locals json.RawMessage) (json.RawMessage, error) {
			calls["finish"]++
			if childPromiseFlow {
				if err := checkPromise(c, locals, 2); err != nil {
					return nil, err
				}
			}
			if bufferedSignals {
				data, err := wf.AwaitSignal(c, "later")
				if err != nil || string(data) != "13" {
					return nil, wf.ErrCorruptJournal
				}
			}
			if string(input) != "7" || !childPromiseFlow && string(locals) != `{"count":2}` {
				return nil, wf.ErrCorruptJournal
			}
			var value int
			ok, err := c.GetState("value", &value)
			if err != nil || !ok || value != 43 {
				return nil, wf.ErrCorruptJournal
			}
			if cancelRunningEffect {
				_, err := wf.RunOnce(c, "running-cancel-once", nil, func(effectCtx context.Context, key string) (int, error) {
					effects++
					close(effectEntered)
					<-effectCtx.Done()
					if lateEffectSuccess {
						return 99, nil
					}
					return 0, effectCtx.Err()
				})
				if err != nil {
					return nil, err
				}
			}
			return json.Marshal(value)
		},
	}}
	leases, err := lease.New(ctx, js)
	if err != nil {
		t.Fatal(err)
	}
	if timerHistory {
		kv, err := js.KeyValue(ctx, "WF_LEASE")
		if err != nil {
			t.Fatal(err)
		}
		leases = lease.NewWithKeyValue(sdkLeaseTraceKV{KeyValue: kv, t: t, js: js})
	}
	executeWorkflow := func(typ, id, workerID string, wakeups ...timerWakeup) bool {
		t.Helper()
		owner, err := leases.Acquire(ctx, typ, id, workerID)
		if err != nil {
			t.Fatal(err)
		}
		var noOp bool
		// Direct calls bypass RunPartition's delivery heartbeat. Match its
		// renewal interval/freshness guard while archive restore reads are active.
		stageCtx, stopStage := context.WithCancel(ctx)
		heartbeatDone := make(chan error, 1)
		go func() {
			ticker := time.NewTicker(runner.heartbeatInterval)
			defer ticker.Stop()
			for {
				select {
				case <-stageCtx.Done():
					heartbeatDone <- nil
					return
				case <-ticker.C:
					renewCtx, stopRenew := context.WithTimeout(stageCtx, 3*time.Second)
					_, renewErr := owner.RenewIfIdle(renewCtx, runner.heartbeatInterval)
					stopRenew()
					if renewErr != nil {
						stopStage()
						heartbeatDone <- renewErr
						return
					}
				}
			}
		}()
		wakeup := timerWakeup{}
		at := time.Time{}
		if len(wakeups) > 0 {
			wakeup = wakeups[0]
			at = time.Now().Add(2 * time.Hour)
		}
		err = runner.execute(stageCtx, typ, id, owner, at, wakeup, &noOp, runner.deliveryOperations(typ, id, 0, 0))
		stopStage()
		heartbeatErr := <-heartbeatDone
		releaseErr := owner.Release(ctx)
		if err != nil && !(cancelRunningEffect && errors.Is(err, context.Canceled)) || releaseErr != nil || heartbeatErr != nil && !errors.Is(heartbeatErr, context.Canceled) {
			t.Fatal("SDK stage delivery", err, releaseErr, heartbeatErr)
		}
		return noOp
	}
	execute := func() { executeWorkflow(h.Type, h.ID, "sdkcontinue") }
	scan, err := reconcile.NewCanonicalContinuationScan(js, graph)
	if err != nil {
		t.Fatal(err)
	}
	runs, err := js.Stream(ctx, "WF_RUN")
	if err != nil {
		t.Fatal(err)
	}
	if partition {
		runCtx, stop := context.WithCancel(ctx)
		done := make(chan error, 1)
		go func() { done <- runner.RunPartition(runCtx, identity.Partition(h.Type, h.ID, provision.Partitions)) }()
		_, awaitErr := c.Await(ctx, h.Type, h.ID)
		stop()
		runErr := <-done
		if awaitErr != nil || runErr != nil && !errors.Is(runErr, context.Canceled) {
			t.Fatal("partition SDK flow", awaitErr, runErr)
		}
	} else {
		for _, stage := range []string{"next", "finish"} {
			phase("execute_begin_" + stage)
			execute()
			phase("execute_end_" + stage)
			status, err := graph.InspectStart(ctx, h.Type, h.ID)
			if err != nil || status.Checkpoint == nil || status.Checkpoint.Stage != stage || !status.ContinuationReady() {
				t.Fatal("SDK did not publish checkpoint", stage, status, err)
			}
			if timerHistory {
				view, err := graph.Open(ctx, h.Type, h.ID, h.InvSeq)
				if err != nil {
					t.Fatal(err)
				}
				found, err := view.ReadCheckpoint(ctx, h.Type, h.ID)
				if err != nil || found == nil {
					t.Fatal("timer frame missing", err)
				}
				var frame checkpoint.Frame
				if err = json.Unmarshal(found.Frame, &frame); err != nil {
					t.Fatal(err)
				}
				want := []uint64{4}
				if stage == "finish" {
					want = append(want, 14)
				}
				a, _ := json.Marshal(frame.CancelledTimers)
				b, _ := json.Marshal(want)
				if !bytes.Equal(a, b) {
					t.Fatal("timer cancellation set", stage, string(a), string(b))
				}
				if err = view.Close(ctx); err != nil {
					t.Fatal(err)
				}
				t.Logf("SDK_TIMER_HISTORY stage=%s cancelled=%s archive=%t", stage, a, archive)
			}
			if pendingChild {
				view, err := graph.Open(ctx, h.Type, h.ID, h.InvSeq)
				if err != nil {
					t.Fatal(err)
				}
				found, err := view.ReadCheckpoint(ctx, h.Type, h.ID)
				if err != nil || found == nil {
					t.Fatal("pending promise checkpoint absent", found, err)
				}
				var frame checkpoint.Frame
				var locals struct {
					Count   int        `json:"count"`
					Promise wf.Promise `json:"promise"`
				}
				wantCount := 1
				if stage == "finish" {
					wantCount = 2
				}
				if json.Unmarshal(found.Frame, &frame) != nil || json.Unmarshal(frame.Data, &locals) != nil || frame.Stage != stage || locals.Count != wantCount || locals.Promise != childPromise || len(frame.PromiseOutcomes) != 0 || len(frame.PendingSignals) != 0 || childCalls != 0 {
					t.Fatal("pending child was resolved or lost before checkpoint", stage, frame, locals, childCalls)
				}
				if err := view.Close(ctx); err != nil {
					t.Fatal(err)
				}
				childStatus, err := graph.InspectStart(ctx, childPromise.ChildType, childPromise.ChildID)
				if err != nil || childStatus.JournalCount != 0 || childStatus.Kind == journal.Completed || childStatus.Kind == journal.Failed {
					t.Fatal("pending child executed before parent checkpoint", childStatus, err)
				}
				t.Logf("PENDING_CHILD_CHECKPOINT stage=%s locals_count=%d child_calls=0 outcomes=0 buffered_signals=0", stage, locals.Count)
			}
			var childReceipts []journal.GraphPayloadLink
			if childPromiseFlow && stage == "finish" && !pendingChild {
				retired, err := graph.InspectRetirement(ctx, childPromise.ChildType, childPromise.ChildID)
				if err != nil {
					t.Fatal(err)
				}
				if archive {
					childView, err := graph.Open(ctx, childPromise.ChildType, childPromise.ChildID, retired.Invocation)
					if err != nil {
						t.Fatal(err)
					}
					terminal, err := childView.Read(ctx, childView.Count()-1)
					if err != nil {
						t.Fatal(err)
					}
					childReceipts = append(terminal.Blobs, terminal.EntryBlob)
					if err = childView.Close(ctx); err != nil {
						t.Fatal(err)
					}
				}
				if err := graph.Retire(ctx, childPromise.ChildType, childPromise.ChildID, retired.Invocation, retired.Tail); err != nil {
					t.Fatal(err)
				}
				phase("child_retire_end")
			}
			if archive {
				// Collect after the worker closed its old pin, then resume from
				// relocated owned receipts on the next independent delivery.
				authority, err := graphpublication.OpenNativeAuthority(ctx, js, cfg.AuthorityStream, cfg.AuthorityPrefix)
				if err != nil {
					t.Fatal(err)
				}
				port, err := graphpublication.OpenNativePort(ctx, authority, cfg.ObjectBucket)
				if err != nil {
					t.Fatal(err)
				}
				protocol := graphpublication.Protocol{Port: port}
				before, err := port.Objects(ctx)
				if err != nil {
					t.Fatal(err)
				}
				if _, err = protocol.SweepWithReaders(ctx, time.Now().Add(2*time.Minute)); err != nil {
					t.Fatal(err)
				}
				if childPromiseFlow && stage == "finish" && !pendingChild {
					for _, receipt := range childReceipts {
						if _, err = port.Get(ctx, receipt, journal.DefaultGraphPayloadLimit); !errors.Is(err, jetstream.ErrObjectNotFound) {
							t.Fatal("retired child receipt absence unconfirmed", receipt, err)
						}
					}
					resultBytes := len(childResult)
					if childFailure {
						resultBytes = 0
					}
					t.Logf("ARCHIVE_CHILD_RECLAIMED terminal_receipts=%d result_bytes=%d", len(childReceipts), resultBytes)
				}
				phase("parent_sweep_end_" + stage)
				view, err := graph.Open(ctx, h.Type, h.ID, h.InvSeq)
				if err != nil {
					t.Fatal(err)
				}
				found, err := view.ReadCheckpoint(ctx, h.Type, h.ID)
				if err != nil || found == nil {
					t.Fatal(found, err)
				}
				keys, err := port.RootKeys(ctx)
				if err != nil {
					t.Fatal(err)
				}
				matched := false
				for _, key := range keys {
					root, err := port.ReadRoot(ctx, key)
					if err != nil {
						t.Fatal(err)
					}
					var cursor struct {
						Invocation   uint64              `json:"invocation"`
						RetainedFrom uint64              `json:"retained_from"`
						Start        *journal.GraphStart `json:"start"`
					}
					if json.Unmarshal(root.Application, &cursor) != nil || cursor.Start == nil || cursor.Start.Request.ID != h.ID || cursor.Start.Request.Type != h.Type {
						continue
					}
					if cursor.Invocation != h.InvSeq || cursor.RetainedFrom != found.Request.Index || root.Graph.Count != view.Count()-found.Request.Index || len(root.Readers) != 1 {
						t.Fatal("worker failed to compact or leaked reader", cursor, root)
					}
					matched = true
				}
				if !matched {
					t.Fatal("compacted parent root absent")
				}
				entryHashes, currentObjects := map[string]bool{}, map[string]bool{}
				audited := uint64(0)
				if err := view.ReadRange(ctx, 0, view.Count(), func(record journal.GraphRecord) error {
					entryHashes[record.EntryBlob.Hash], currentObjects[record.EntryBlob.Reference.Object] = true, true
					audited++
					return nil
				}); err != nil || audited != view.Count() {
					t.Fatal("audit after collection", audited, view.Count(), err)
				}
				removedEntries := 0
				for _, object := range before {
					if entryHashes[object.Key] && !currentObjects[object.Reference.Object] {
						if _, err = port.Get(ctx, retainedgraph.Link{Hash: object.Key, Reference: object.Reference}, journal.MaxGraphEntryBytes); !errors.Is(err, jetstream.ErrObjectNotFound) {
							t.Fatal("original entry receipt absence unconfirmed", object, err)
						}
						removedEntries++
					}
				}
				if removedEntries == 0 {
					t.Fatal("collection had no original entry receipts")
				}
				t.Logf("ARCHIVE_COLLECTION stage=%s original_entry_receipts_removed=%d live_records=%d logical_records=%d", stage, removedEntries, view.Count()-found.Request.Index, view.Count())
				if err = view.Close(ctx); err != nil {
					t.Fatal(err)
				}
				phase("parent_audit_end_" + stage)
			}
			if err := runs.Purge(ctx); err != nil {
				t.Fatal(err)
			}
			budget := 1
			if childPromiseFlow {
				budget = 4
			}
			result, err := scan.Scan(ctx, 1, budget, false)
			if err != nil || result.Reenqueued != 1 {
				t.Fatal("SDK boundary wakeup not recovered", stage, result, err)
			}
			phase("boundary_scan_end_" + stage)
			if cancelledWakeup {
				steps := []uint64{4}
				if stage == "finish" {
					steps = append(steps, 14)
				}
				for _, step := range steps {
					before, _, err := graph.ReadExisting(ctx, h.Type, h.ID, h.InvSeq)
					if err != nil {
						t.Fatal(err)
					}
					priorCalls, priorEffects := fmt.Sprint(calls), effects
					noOp := executeWorkflow(h.Type, h.ID, "cancelled-wakeup", timerWakeup{scheduled: true, generation: h.InvSeq, step: step})
					after, _, err := graph.ReadExisting(ctx, h.Type, h.ID, h.InvSeq)
					if err != nil {
						t.Fatal(err)
					}
					a, _ := json.Marshal(before)
					b, _ := json.Marshal(after)
					if !noOp || !bytes.Equal(a, b) || effects != priorEffects || fmt.Sprint(calls) != priorCalls {
						t.Fatal("cancelled timer reentered archived handler", stage, step, noOp, calls, effects)
					}
					t.Logf("SDK_CANCELLED_TIMER_WAKEUP stage=%s step=%d no_op=true immutable_history=true unchanged_effects=true archive=true", stage, step)
				}
			}

			if childPromiseFlow {
				if stage == "next" && !pendingChild {
					executeWorkflow(childPromise.ChildType, childPromise.ChildID, "sdkchild")
					phase("child_execute_end")
				}
			}
			if bufferedSignals && stage == "next" {
				if _, err := c.Signal(ctx, h.Type, h.ID, "later", []byte(`13`), "later"); err != nil {
					t.Fatal(err)
				}
			}
		}
		if cancelRunningEffect {
			// Remove the best-effort notification; recovery must use durable polling.
			if err := runner.Close(); err != nil {
				t.Fatal(err)
			}
			prefix, _, err := graph.ReadExisting(ctx, h.Type, h.ID, h.InvSeq)
			if err != nil {
				t.Fatal(err)
			}
			done := make(chan struct{})
			go func() { defer close(done); execute() }()
			select {
			case <-effectEntered:
			case <-ctx.Done():
				t.Fatal("restored effect never entered", ctx.Err())
			}
			sequence, err := c.Cancel(ctx, h.Type, h.ID)
			if err != nil || sequence == 0 {
				t.Fatal("running cancellation not acknowledged", sequence, err)
			}
			// Canonical ownership must survive removal of its compatibility pointer.
			signalStream, err := js.Stream(ctx, "WF_SIG")
			if err != nil {
				t.Fatal(err)
			}
			if err := signalStream.DeleteMsg(ctx, sequence); err != nil {
				t.Fatal(err)
			}
			if _, err := signalStream.GetMsg(ctx, sequence); !errors.Is(err, jetstream.ErrMsgNotFound) {
				t.Fatal("cancel pointer removal unconfirmed", err)
			}

			select {
			case <-done:
			case <-ctx.Done():
				t.Fatal("running effect failed to observe cancellation", ctx.Err())
			}
			// A cancelled handler is intentionally abandoned. Its next delivery
			// drains the durable cancel before entering user code.
			execute()
			result, err := c.Await(ctx, h.Type, h.ID)
			if !errors.Is(err, client.ErrCancelled) || len(result) != 0 {
				t.Fatal("running cancellation outcome", string(result), err)
			}
			records, _, err := graph.ReadExisting(ctx, h.Type, h.ID, h.InvSeq)
			if err != nil || len(records) <= len(prefix) {
				t.Fatal("running cancellation history", err)
			}
			a, _ := json.Marshal(prefix)
			b, _ := json.Marshal(records[:len(prefix)])
			if !bytes.Equal(a, b) {
				t.Fatal("running cancellation changed checkpoint prefix")
			}
			terminals, cancellations, requests, completions := 0, 0, 0, 0
			for i, record := range records {
				if record.Index != uint64(i) {
					t.Fatal("running cancellation absolute index", record)
				}
				if record.Kind == journal.Completed || record.Kind == journal.Failed {
					terminals++
				}
				var event struct {
					Name string `json:"name"`
				}
				if json.Unmarshal(record.Payload, &event) == nil {
					if record.Kind == journal.SignalConsumed && event.Name == client.CancelSignalName {
						cancellations++
					}
					if record.Kind == journal.StepRequested && event.Name == "running-cancel-once" {
						requests++
					}
				}
				if record.Kind == journal.StepCompleted && i > 0 {
					var declaration struct {
						Name string `json:"name"`
					}
					if json.Unmarshal(records[i-1].Payload, &declaration) == nil && declaration.Name == "running-cancel-once" {
						completions++
					}
				}
			}
			var outcome wf.Outcome
			tail := records[len(records)-1]
			if tail.Kind != journal.Failed || json.Unmarshal(tail.Payload, &outcome) != nil || outcome.InvSeq != h.InvSeq || outcome.Error != client.ErrCancelled.Error() || terminals != 1 || cancellations != 1 || requests != 1 {
				t.Fatal("running cancellation terminal/consumption", outcome, terminals, cancellations, requests, completions)
			}
			if calls["initial"] != 1 || calls["next"] != 1 || calls["finish"] != 1 || effects != 3 {
				t.Fatal("running cancellation repeated handler/effect", calls, effects)
			}
			before, _ := json.Marshal(records)
			execute()
			after, _, err := graph.ReadExisting(ctx, h.Type, h.ID, h.InvSeq)
			afterBytes, _ := json.Marshal(after)
			if err != nil || !bytes.Equal(before, afterBytes) || effects != 3 || calls["finish"] != 1 {
				t.Fatal("duplicate reactivated cancelled running effect", err, calls, effects)
			}
			t.Logf("RUNNING_EFFECT_CANCELLED archive=%t late_success=%t prefix_records=%d records=%d terminals=1 cancellations=1 requests=1 effect_completions=%d effects=3 initial=1 next=1 finish=1 immutable_duplicate=true notification_disabled=true source_removed=true retried=true", archive, lateEffectSuccess, len(prefix), len(records), completions)
			return
		}

		if pendingChild {
			execute() // The restored finish stage must wait, never complete early.
			var err error
			pendingPrefix, _, err = graph.ReadExisting(ctx, h.Type, h.ID, h.InvSeq)
			if err != nil || len(pendingPrefix) == 0 {
				t.Fatal("pending parent history absent", err)
			}
			last := pendingPrefix[len(pendingPrefix)-1]
			var wait struct {
				WaitingOn string `json:"waiting_on"`
			}
			if last.Kind != journal.Suspended || json.Unmarshal(last.Payload, &wait) != nil || wait.WaitingOn != "signal:"+childPromise.SignalName || childCalls != 0 || effects != 2 || calls["initial"] != 1 || calls["next"] != 1 || calls["finish"] != 1 {
				t.Fatal("parent did not suspend for unresolved child", last, wait, calls, effects, childCalls)
			}
			status, err := graph.InspectStart(ctx, h.Type, h.ID)
			if err != nil || status.Kind != journal.Suspended || status.ContinuationReady() {
				t.Fatal("child wait incorrectly became checkpoint boundary wakeup", status, err)
			}
			t.Logf("PENDING_CHILD_SUSPENDED records=%d effects=2 child_calls=0 waiting_on=%s", len(pendingPrefix), wait.WaitingOn)
			if cancelPendingChild {
				sequence, err := c.Cancel(ctx, h.Type, h.ID)
				if err != nil || sequence == 0 {
					t.Fatal("pending parent cancellation not acknowledged", sequence, err)
				}
				if err := runs.Purge(ctx); err != nil {
					t.Fatal(err)
				}
				signalScan, err := reconcile.NewCanonicalSignalScan(js, graph)
				if err != nil {
					t.Fatal(err)
				}
				recovered, err := signalScan.Scan(ctx, 1, 4, false)
				if err != nil || recovered.Reenqueued != 1 {
					t.Fatal("pending cancellation wakeup not recovered", recovered, err)
				}
				t.Log("PENDING_PARENT_CANCEL_WAKEUP_RECOVERED reenqueued=1")
				execute()
				result, err := c.Await(ctx, h.Type, h.ID)
				if !errors.Is(err, client.ErrCancelled) || len(result) != 0 || calls["initial"] != 1 || calls["next"] != 1 || calls["finish"] != 1 || effects != 2 || childCalls != 0 {
					t.Fatal("pending cancellation ran another stage or changed outcome", result, err, calls, effects, childCalls)
				}
				cancelled, _, err := graph.ReadExisting(ctx, h.Type, h.ID, h.InvSeq)
				if err != nil || len(cancelled) <= len(pendingPrefix) {
					t.Fatal("cancellation history absent", cancelled, err)
				}
				prefixBytes, _ := json.Marshal(pendingPrefix)
				preserved, _ := json.Marshal(cancelled[:len(pendingPrefix)])
				if !bytes.Equal(prefixBytes, preserved) {
					t.Fatal("pending prefix changed during cancellation")
				}
				terminal := cancelled[len(cancelled)-1]
				var outcome wf.Outcome
				if terminal.Kind != journal.Failed || json.Unmarshal(terminal.Payload, &outcome) != nil || outcome.InvSeq != h.InvSeq || outcome.Error != client.ErrCancelled.Error() {
					t.Fatal("wrong canonical cancellation terminal", terminal, outcome)
				}
				terminals, cancellations := 0, 0
				for i, record := range cancelled {
					if record.Index != uint64(i) {
						t.Fatal("cancelled parent absolute index changed", record)
					}
					if record.Kind == journal.Completed || record.Kind == journal.Failed {
						terminals++
					}
					var consumed struct {
						Name string `json:"name"`
					}
					if record.Kind == journal.SignalConsumed && json.Unmarshal(record.Payload, &consumed) == nil && consumed.Name == client.CancelSignalName {
						cancellations++
					}
				}
				if terminals != 1 || cancellations != 1 {
					t.Fatal("duplicate cancellation or terminal publication", terminals, cancellations)
				}
				t.Logf("PENDING_PARENT_CANCELLED prefix_records=%d records=%d initial=1 next=1 finish=1 effects=2 child_calls=0 terminals=1 cancel_signals=1", len(pendingPrefix), len(cancelled))
				// v1 does not cancel children with their parent. A late outcome
				// must preserve the parent's immutable cancelled generation.
				executeWorkflow(childPromise.ChildType, childPromise.ChildID, "sdkchild")
				checkChildOutcome := func() {
					t.Helper()
					result, err := c.Await(ctx, childPromise.ChildType, childPromise.ChildID)
					if childFailure {
						if err == nil || err.Error() != "planned child failure" || len(result) != 0 {
							t.Fatal("cancelled parent changed independent child failure", result, err)
						}
					} else {
						var value string
						if err != nil || json.Unmarshal(result, &value) != nil || value != childResult {
							t.Fatal("cancelled parent changed independent child result", len(result), err)
						}
					}
				}
				checkChildOutcome()
				if archive {
					authority, err := graphpublication.OpenNativeAuthority(ctx, js, cfg.AuthorityStream, cfg.AuthorityPrefix)
					if err != nil {
						t.Fatal(err)
					}
					port, err := graphpublication.OpenNativePort(ctx, authority, cfg.ObjectBucket)
					if err != nil {
						t.Fatal(err)
					}
					protocol := graphpublication.Protocol{Port: port}
					if _, err := protocol.SweepWithReaders(ctx, time.Now().Add(2*time.Minute)); err != nil {
						t.Fatal(err)
					}
					checkChildOutcome()
					t.Log("PENDING_PARENT_CANCEL_COLLECTION child_outcome_preserved=true")
				}
				executeWorkflow(childPromise.ChildType, childPromise.ChildID, "sdkchild-duplicate")
				execute()
				fresh, err := client.New(js).WithGraphJournal(graph)
				if err != nil {
					t.Fatal(err)
				}
				result, err = fresh.Await(ctx, h.Type, h.ID)
				if !errors.Is(err, client.ErrCancelled) || len(result) != 0 || childCalls != 1 || calls["finish"] != 1 || effects != 2 {
					t.Fatal("late child or duplicate reactivated cancelled parent", result, err, childCalls, calls, effects)
				}
				after, _, err := graph.ReadExisting(ctx, h.Type, h.ID, h.InvSeq)
				beforeBytes, _ := json.Marshal(cancelled)
				afterBytes, _ := json.Marshal(after)
				if err != nil || !bytes.Equal(beforeBytes, afterBytes) {
					t.Fatal("late child mutated cancelled parent history", err)
				}
				legacy, err := js.Stream(ctx, "WF_JRN")
				if err != nil {
					t.Fatal(err)
				}
				info, err := legacy.Info(ctx)
				if err != nil || info.State.Msgs != 0 {
					t.Fatal("cancelled continuation wrote legacy history", info, err)
				}
				t.Logf("PENDING_PARENT_CANCEL_CHILD_INDEPENDENT failed=%t archive=%t child_calls=1 parent_records=%d parent_error=workflow_cancelled effects=2", childFailure, archive, len(after))
				return
			}
			executeWorkflow(childPromise.ChildType, childPromise.ChildID, "sdkchild")
			phase("pending_child_execute_end")
			if err := runs.Purge(ctx); err != nil {
				t.Fatal(err)
			}
			signalScan, err := reconcile.NewCanonicalSignalScan(js, graph)
			if err != nil {
				t.Fatal(err)
			}
			recovered, err := signalScan.Scan(ctx, 1, 4, false)
			if err != nil || recovered.Reenqueued != 1 {
				t.Fatal("pending child outcome wakeup not recovered", recovered, err)
			}
			t.Log("PENDING_CHILD_WAKEUP_RECOVERED reenqueued=1")
		}
		execute()
	}
	execute() // Completion followed by an independently fenced duplicate.
	result, err := c.Await(ctx, h.Type, h.ID)
	wantFinish := 1
	if pendingChild {
		wantFinish = 2
	}
	wantInitial := 1
	if positiveTimer {
		wantInitial = 2
	}
	if err != nil || string(result) != "43" || effects != 2 || calls["initial"] != wantInitial || calls["next"] != 1 || calls["finish"] != wantFinish {
		t.Fatal("SDK workflow replay/result", string(result), err, calls, effects)
	}
	records, _, err := graph.ReadExisting(ctx, h.Type, h.ID, h.InvSeq)
	if err != nil {
		t.Fatal(err)
	}
	if pendingChild {
		if len(records) <= len(pendingPrefix) {
			t.Fatal("child completion did not extend parent history")
		}
		for i, original := range pendingPrefix {
			// Collection may relocate owned receipts; logical bytes and the
			// publication sequence/epoch/index are immutable across resume.
			current := records[i]
			if current.Index != original.Index || current.Epoch != original.Epoch || current.Sequence != original.Sequence || current.Kind != original.Kind || !bytes.Equal(current.Payload, original.Payload) {
				t.Fatal("pending prefix changed on child resume", i, original, current)
			}
		}
		t.Logf("PENDING_CHILD_RESUMED failed=%t archive=%t prefix_records=%d records=%d initial=1 next=1 finish=2 effects=2 child_calls=%d result=43", childFailure, archive, len(pendingPrefix), len(records), childCalls)
	}
	if positiveTimer {
		suspended, handoffs, starts := 0, 0, 0
		var deadline time.Time
		for _, record := range records {
			if record.Kind == journal.Suspended {
				var wait struct {
					WaitingOn string `json:"waiting_on"`
				}
				if json.Unmarshal(record.Payload, &wait) != nil {
					t.Fatal("invalid suspension payload")
				}
				switch wait.WaitingOn {
				case "timer:initial-fire":
					suspended++
				case "continuation:next", "continuation:finish":
					handoffs++
				default:
					t.Fatal("unexpected suspension", wait.WaitingOn)
				}
			}
			if record.Kind == journal.StepRequested {
				var request struct {
					Kind     string    `json:"kind"`
					Name     string    `json:"name"`
					Duration int64     `json:"duration_nanos"`
					FireAt   time.Time `json:"fire_at"`
				}
				if json.Unmarshal(record.Payload, &request) == nil && request.Kind == "timer_start" && request.Name == "initial-fire" {
					starts++
					deadline = request.FireAt
					if request.Duration != int64(75*time.Millisecond) || deadline.IsZero() {
						t.Fatal("positive timer request", request)
					}
				}
			}
		}
		if suspended != 1 || handoffs != 2 || starts != 1 || runner.metrics.timersScheduled.Load() != 3 {
			t.Fatal("timer did not suspend/schedule exactly once", suspended, handoffs, starts, runner.metrics.timersScheduled.Load())
		}
		t.Logf("SDK_POSITIVE_TIMER suspended=1 handoffs=2 start=1 schedules=3 initial=2 next=1 finish=1 effects=2 deadline=%s", deadline.Format(time.RFC3339Nano))
	}
	completions := 0
	for i, record := range records {
		if record.Index != uint64(i) {
			t.Fatal("absolute journal index changed", record)
		}
		if record.Kind == journal.Completed {
			completions++
		}
	}
	if completions != 1 {
		t.Fatal("terminal append repeated", completions)
	}
	legacy, err := js.Stream(ctx, "WF_JRN")
	if err != nil {
		t.Fatal(err)
	}
	info, err := legacy.Info(ctx)
	if err != nil || info.State.Msgs != 0 {
		t.Fatal("SDK flow wrote legacy journal", info, err)
	}
	if childPromiseFlow && childCalls != 1 {
		t.Fatal("child was replayed", childCalls)
	}
	if os.Getenv("WF_GRAPH_SDK_RAW_AUDIT") == "1" {
		if err := runner.Close(); err != nil {
			t.Fatal(err)
		}
		report, err := integrity.CheckNativeGraphJournals(ctx, js, integrity.GraphAuditNamespace{AuthorityStream: cfg.AuthorityStream, AuthorityPrefix: cfg.AuthorityPrefix, ObjectBucket: cfg.ObjectBucket, PayloadLimit: checkpoint.MaxBytes})
		if err != nil || report.Pending != 0 || report.Terminal == 0 {
			t.Fatal("independent SDK runtime audit", report, err)
		}
		if !childPromiseFlow && !cancelRunningEffect && report.Checkpoints != 2 {
			t.Fatal("historical SDK checkpoint census", report.Checkpoints)
		}
		t.Logf("RAW_SDK_CHECKPOINT_AUDIT journals=%d entries=%d terminals=%d pending=%d retired_projection_only=%d", report.Journals, report.Entries, report.Terminal, report.Pending, report.RetiredProjectionOnly)
		t.Logf("RAW_SDK_CHECKPOINT_HISTORY checkpoints=%d", report.Checkpoints)
	}
	t.Logf("SDK initial/next/finish=%v effects=%d records=%d result=%s", calls, effects, len(records), result)
	if childFailure {
		t.Logf("GRAPH_FAILED_CHILD buffered=%t archive=%t child_calls=%d preserved_error=planned_child_failure parent_result=%s", bufferedChild, archive, childCalls, result)
	}
}
