from pathlib import Path
import json,hashlib,subprocess,shutil
repo=Path('/home/exedev/js-wf');root=Path('/tmp/js-wf-state-watch-leader-loss-copied-20261005');out=repo/'docs/scale/state-watch-leader-loss-2026-10-05';out.mkdir()
def sha(p):return hashlib.file_digest(p.open('rb'),'sha256').hexdigest()
e=json.loads((root/'execution.json').read_text());assert e['status']=='failed' and e['exit_code']==1 and e['live_servers_captured'];assert sha(root/'integrity.test')==e['sha256'] and 'vcs.modified=false' in e['build_info']
before=json.loads((root/'source-before.json').read_text());assert before==json.loads((root/'source-after.json').read_text()) and before['revision']==e['source']
for n,d in before['files'].items():assert sha(root/'source'/n)==hashlib.sha256(subprocess.check_output(['git','show',e['source']+':'+n],cwd=repo)).hexdigest()==d
servers=json.loads((root/'actual-containers/actual-servers.json').read_text());assert len(servers)==5 and all(s['sha256']=='751a788956b200d9ed08fa7dff4587b772b98e1b3e82cef6ff15b69be052f42d' for s in servers)
proof=json.loads(next((root/'originals').rglob('state-watch-leader-loss.json')).read_text());f=proof['fault'];assert f['triggered'] and not f['injection_error'] and f['consumer']['num_pending']>0 and f['consumer']['config']['num_replicas']==1 and f['consumer']['config']['mem_storage'] and f['kill']['source_stopped'];assert len(proof['attempts'])==1 and proof['attempts'][0]['records']==11685 and not proof['attempts'][0]['complete'];assert proof['values']==0 and 'context deadline exceeded' in proof['error'];assert json.loads((root/'original-after-verification.json').read_text())['all_original_store_bytes_still_match']
review={'source':e['source'],'actual_sdk_sha256':e['sha256'],'five_actual_native_server_executables_and_builds_retained':True,'selected_git_inputs_verified':len(before['files']),'copied_store_leader_loss_proof':proof,'original_store_bytes_unchanged':True,'native_failed_seconds':17.18,'watch_partial_initial_completion_false':True,'snapshot_elapsed_ns':proof['elapsed_ns'],'production_budgets_changed':False,'historical_24h_cause_confirmed':False,'secondary_cleanup_error':'Killed container had been removed, so its post-cut docker log capture failed; other four logs retained. This is additional to the snapshot failure.','qualifies_fault_recovery':False,'qualifies_full_matrix_or_24h':False,'no_unchanged_rerun':True}
(root/'independent-review.json').write_text(json.dumps(review,indent=2)+'\n');shutil.copy2(__file__,root/'executed-review.py');shutil.copy2(root/'independent-review.json',out/'independent-review.json');shutil.copy2(next((root/'originals').rglob('state-watch-leader-loss.json')),out/'state-watch-leader-loss.json');shutil.copy2(__file__,out/'executed-review.py');shutil.copy2('/tmp/js-wf-run-state-watch-leader-loss-copied-20261005.py',out/'executed-producer.py');shutil.copy2('/tmp/js-wf-preserve-read-proof-20261005.py',out/'executed-preserver.py');print(json.dumps(review))
