from pathlib import Path
import hashlib,json,subprocess,re,shutil
repo=Path('/home/exedev/js-wf');r=Path('/tmp/js-wf-retirement-before-manifest-repair-race-20261005')
def sha(p):
 with p.open('rb') as f:return hashlib.file_digest(f,'sha256').hexdigest()
e=json.loads((r/'execution.json').read_text());assert e['status']=='passed' and e['exit_code']==0
b=json.loads((r/'binary.json').read_text());assert b['sha256']==e['exe_sha256']==sha(r/'integrity.test');info=subprocess.check_output(['go','version','-m',str(r/'integrity.test')],text=True);assert info==b['build_info'] and '-race=true' in info and f"vcs.revision={e['revision']}" in info and 'vcs.modified=false' in info
before=json.loads((r/'source-before.json').read_text());after=json.loads((r/'source-after.json').read_text());assert before==after and before['revision']==e['revision']
for n,d in before['files'].items():assert sha(r/'source'/n)==sha(repo/n)==hashlib.sha256(subprocess.check_output(['git','show',e['revision']+':'+n],cwd=repo)).hexdigest()==d
servers=json.loads((r/'originals/actual-servers.json').read_text());assert len(servers)==3 and {x['node'] for x in servers}=={0,1,2} and len({x['pid'] for x in servers})==3 and len({x['sha256'] for x in servers})==1
server=r/'originals/cluster/nats-server';assert sha(server)==servers[0]['sha256'];server_info=subprocess.check_output(['go','version','-m',str(server)],text=True).splitlines()[1:]
for s in servers:assert s['build_info'].splitlines()[1:]==server_info and s['args'][0]==str(server)
k=json.loads((r/'originals/kill-admission.json').read_text());q=json.loads((r/'originals/result.json').read_text())
assert k['signal']=='SIGKILL' and k['cut']=='before_manifest' and k['child_live_sdk_sha256']==k['parent_sdk_sha256']==e['exe_sha256'] and k['child_pid']!=e['pid'] and k['lease_ttl']=='12s'
assert q['old_generation']==k['old_generation']==1 and q['fresh_generation']==k['fresh_generation']==3 and q['held_epoch']==k['held_epoch'] and q['terminal_epoch']>q['held_epoch']>0
assert q['reclaimed_objects']==k['reclaimed_objects']==2 and 0<q['recovery_seconds']<30 and not q['bounded_resume_required'] and q['prepared_frame_reused'] and not q['read_counters_observed'] and q['prepared_frame']==k['prepared_frame'] and q['completed_frame']==q['prepared_frame'] and bool(q['prepared_frame']) and not k['manifest_published'] and q['effects']==3 and q['terminals']==q['invocations']==2 and q['shared_and_survivor_and_fresh_references_verified'] and q['all_peer_fresh_results_verified']
ledger=(r/'originals/effects.log').read_text().splitlines();counts={line:ledger.count(line) for line in set(ledger)};assert counts==q['ledger_counts']=={'initial:1':2,'effect:1':2,'stage:1':2,'initial:2':2,'effect:2':1,'stage:2':1}
prepared=json.loads((r/'originals/cut.manifest').read_text());assert prepared['runtime_checkpoint']['inv_seq']==3 and prepared['runtime_checkpoint']['object']==q['prepared_frame']
log=(r/'native.log').read_text();assert '\nPASS\n' in log;elapsed=float(re.search(r'--- PASS: TestContinuationRetirementReuseBeforeManifestWorkerSIGKILL \(([0-9.]+)s\)',log)[1])
review={'source':e['revision'],'actual_live_parent_sdk_sha256':e['exe_sha256'],'actual_live_child_sdk_sha256':k['child_live_sdk_sha256'],'clean_full_build_info_and_race_verified':True,'source_inputs':len(before['files']),'source_before_after_and_git_match':True,'actual_native_server_processes':3,'actual_native_server_sha256':servers[0]['sha256'],'all_live_server_and_retained_binary_build_fields_match':True,'named_pass_seconds':elapsed,'kill_admission':k,'result':q,'exact_effect_ledger_verified':True,'kill_and_fence_scope':'Named-test actual reaped SIGKILL WaitStatus, prepared fresh generation frame present but no manifest published, held owner before cut, recorded frame reuse and quiescent GC retention verified, terminal epoch above held epoch after successor recovery','physical_stores_scope':'Stopped originals archived/hash-verified, not independently reopened','scope':'Focused retirement/quiescent-GC/generation-reuse plus worker SIGKILL before fresh manifest publication; archive/frame counters unobserved placeholders, no bounded resume claim; not every retirement timing cut, server simultaneous outage, online GC, domain/legacy faults, full matrices or24h qualification. Production TTL12/heartbeat3/AckWait13 and original30s startup/60s scenario/under30 recovery unchanged; Tier1 graph unchanged'}
(r/'qualification.json').write_text(json.dumps(review,indent=2)+'\n');shutil.copyfile(__file__,r/'executed-review.py');print('QUALIFIED',elapsed,q['recovery_seconds'],len(before['files']),q['held_epoch'],q['terminal_epoch'])
